import routes from './routes';
import marketplaceLanding from './landing/LandingPageContainer';
import marketplaceCompare from './compare/ComparisonContainer';
import comparisonIndicator from './compare/ComparisonIndicator';
import marketplaceCheckout from './cart/CheckoutPage';
import cartIndicator from './cart/ShoppingCartIndicator';
import marketplaceOffering from './details/DetailsPage';
import marketplaceList from './list/ListPage';
import marketplaceProviderDetails from './service-providers/ProviderDetailsContainer';
import marketplaceVendorOfferings from './offerings/OfferingsList';
import marketplaceOfferingCreate from './offerings/OfferingCreateContainer';
import marketplaceOrdersList from './orders/OrdersList';
import marketplaceOrderDetails from './orders/OrderDetailsContainer';
import providersService from './providers-service';
import registerSidebarExtension from './sidebar';
import shoppingCartConfig from './shoppingCartConfig';

export default module => {
  module.component('marketplaceLanding', marketplaceLanding);
  module.component('marketplaceCompare', marketplaceCompare);
  module.component('comparisonIndicator', comparisonIndicator);
  module.component('marketplaceCheckout', marketplaceCheckout);
  module.component('cartIndicator', cartIndicator);
  module.component('marketplaceOffering', marketplaceOffering);
  module.component('marketplaceList', marketplaceList);
  module.component('marketplaceProviderDetails', marketplaceProviderDetails);
  module.component('marketplaceVendorOfferings', marketplaceVendorOfferings);
  module.component('marketplaceOfferingCreate', marketplaceOfferingCreate);
  module.component('marketplaceOrdersList', marketplaceOrdersList);
  module.component('marketplaceOrderDetails', marketplaceOrderDetails);
  module.service('providersService', providersService);
  module.config(routes);
  module.run(registerSidebarExtension);
  module.run(shoppingCartConfig);
};
