export const STATE_TEMPLATES = {
  attach: gettext('Attaching'),
  create_snapshot_schedule: gettext('Creating snapshot schedule'),
  update: gettext('Updating'),
  snapshot: gettext('Taking a snapshot'),
  pull: gettext('Pulling'),
  import_resource: gettext('Importing resources'),
  extend: gettext('Extending'),
  detach: gettext('Detaching'),
  destroy: gettext('Destroying'),
  restore: gettext('Restroing'),
  change_flavor: gettext('Changing flavor'),
  start: gettext('Starting'),
  stop: gettext('Stopping'),
  restart: gettext('Restarting'),
  update_security_groups: gettext('Updating security groups'),
  backup: gettext('Backing up'),
  create_backup_schedule: gettext('Creating a backup schedule'),
  update_internal_ips_set: gettext('Updating internal IPs'),
  update_floating_ips: gettext('Updating floaating IPs'),
  activate: gettext('Activating'),
  deactivate: gettext('Deactivating'),
  set_rules: gettext('Updating rules'),
  set_quotas: gettext('Updating quotas'),
  create_network: gettext('Creating a new network'),
  create_subnet: gettext('Creating a subnet'),
  create_floating_ip: gettext('Creating a floating IP'),
  create_security_group: gettext('Creating a security group'),
  change_password: gettext('Changing password'),
  pull_quotas: gettext('Pulling quotas'),
};
