include:
  - project: "waldur/waldur-pipelines"
    file: "/templates/stages.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/release/publish-multiarch.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/validate/docker-compose-trigger.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/test/lint-docker-image.yaml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/test/lint-dockerfile.yaml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/test/lint-md-files.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/deploy/dev-env-update.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/sbom/upload-sboms-to-docs.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/sbom/generate-image-sbom.yml"
variables:
  COMPONENT_VERSION: "latest"

image: registry.hpc.ut.ee/mirror/library/node:lts-alpine3.22

cache:
  key: "$CI_COMMIT_REF_NAME"
  policy: pull
  paths:
    - .yarn
    - node_modules/

before_script:
  - apk add git || echo "Non-Alpine image, skipping"
  - yarn config set cache-folder .yarn
  - yarn install --frozen-lockfile

Run linters:
  stage: test
  interruptible: true
  rules:
    - if: '$SKIP_TESTS == "true" || $SKIP_TESTS == "yes"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - src/**/*.css
        - src/**/*.scss
        - src/**/*.ts
        - src/**/*.tsx
        - package.json
        - yarn.lock
        - tsconfig.json
        - typings.d.ts
        - vite.config.ts
        - .eslintrc.cjs
        - .eslintignore
  script:
    - yarn oxlint
    - yarn format:check
    - yarn tsc -b
    - yarn lint:check
    - yarn style:check
    - yarn deps:unused
    - yarn deps:circular

Run code duplication detection:
  stage: test
  interruptible: true
  rules:
    - if: '$SKIP_TESTS == "true" || $SKIP_TESTS == "yes"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - src/**/*.css
        - src/**/*.scss
        - src/**/*.ts
        - src/**/*.tsx
        - .gitlab-ci.yml
  script:
    - npm install -g jscpd
    - npx jscpd src/ --exitCode 1 -r consoleFull --pattern "**/*.scss"
    - npx jscpd src/ --exitCode 1 -r consoleFull --pattern "**/*.tsx" -k 250

Run unit tests:
  stage: test
  interruptible: true
  rules:
    - if: '$SKIP_TESTS == "true" || $SKIP_TESTS == "yes"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - src/**/*.css
        - src/**/*.scss
        - src/**/*.ts
        - src/**/*.tsx
        - package.json
        - yarn.lock
        - tsconfig.json
        - typings.d.ts
        - vite.config.ts
        - test/*
      allow_failure: true
  script:
    - yarn vitest --run --reporter junit --outputFile junit.xml
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  artifacts:
    when: always
    paths:
      - junit.xml
    reports:
      junit: junit.xml

Run E2E tests:
  image:
    name: registry.hpc.ut.ee/mirror/cypress/included:14.5.0
    entrypoint: [""]
  stage: test
  interruptible: true
  rules:
    - if: '$SKIP_TESTS == "true" || $SKIP_TESTS == "yes"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - src/**/*.css
        - src/**/*.scss
        - src/**/*.ts
        - src/**/*.tsx
        - package.json
        - yarn.lock
        - tsconfig.json
        - typings.d.ts
        - vite.config.ts
        - cypress/**/*
        - cypress.config.js
      allow_failure: true
  script:
    - NO_COLOR=1 yarn ci:test
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos
    reports:
      junit:
        - cypress/results/output-*.xml

Build artifact:
  stage: build
  interruptible: true
  rules:
    - if: '$SKIP_TESTS == "true" || $SKIP_TESTS == "yes"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop"'
  script:
    - yarn build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

Publish latest multiarch docker image:
  extends: .Publish multiarch latest docker image template
  variables:
    EXTRA_BUILD_ARGS: "--build-arg COMMIT_INFO=${CI_COMMIT_SHA} --build-arg VERSION=latest"

Publish multiarch docker image with specific version:
  extends: .Publish multiarch docker image with specific version template
  variables:
    EXTRA_BUILD_ARGS: "--build-arg COMMIT_INFO=${CI_COMMIT_TAG} --build-arg VERSION=${CI_COMMIT_TAG}"

Test Multi-arch docker image build:
  stage: test
  interruptible: true
  image: registry.hpc.ut.ee/mirror/docker:latest
  services:
    - name: "docker:dind"
      command: ["--mtu=1400"]
  rules:
    # Skip tests if said so
    - if: '$SKIP_TESTS == "true" || $SKIP_TESTS == "yes"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - Dockerfile
        - docker/**/*
        - .gitlab-ci.yml
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_REGISTRY: registry.hpc.ut.ee/mirror/
    DOCKER_HUB_REGISTRY: "docker.io"
  cache: []
  before_script:
    - apk update
    - apk add --no-cache gcc python3-dev musl-dev linux-headers openldap-dev openssl libffi-dev libjpeg-turbo-dev libxml2-dev libxslt-dev
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker context create builder
    - docker buildx version
    - docker buildx create builder --use
    - docker buildx build --platform linux/amd64,linux/arm64 --build-arg DOCKER_REGISTRY=$DOCKER_REGISTRY -t ${CI_REGISTRY_IMAGE}:${CI_MERGE_REQUEST_ID}-multiarch --push .
    - docker buildx imagetools inspect ${CI_REGISTRY_IMAGE}:${CI_MERGE_REQUEST_ID}-multiarch
    - docker pull ${CI_REGISTRY_IMAGE}:${CI_MERGE_REQUEST_ID}-multiarch
    - docker image inspect ${CI_REGISTRY_IMAGE}:${CI_MERGE_REQUEST_ID}-multiarch
    
Lint docker image:
  extends: .Lint docker image template
  variables:
    IMAGE: opennode/waldur-homeport:latest
    DOCKERFILE: Dockerfile
  before_script: []

Lint dockerfile:
  extends: .Lint dockerfile template
  variables:
    DOCKERFILE: Dockerfile
    HADOLINT_CONFIG: |
      ignored:
        - DL3018 # "versions for `apk add`" warning
  before_script: []

Generate Image SBOM:
  extends: .Generate Image SBOM template
  variables:
    PROJECT_NAME: "waldur-homeport"

Generate Codebase SBOM:
  stage: build
  image: registry.hpc.ut.ee/mirror/library/node:lts-alpine
  interruptible: true
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
  cache: []
  before_script: []
  script:
    - apk add git || echo "Non-Alpine image, skipping"
    - yarn set version berry
    - yarn install --no-immutable
    - yarn dlx -q @cyclonedx/yarn-plugin-cyclonedx --spec-version 1.6 --output-file waldur-homeport-${CI_COMMIT_TAG}-source.cyclonedx.json -v
    - echo "SBOM generated. Size:"
    - du -h waldur-homeport-${CI_COMMIT_TAG}-source.cyclonedx.json
    - tar -czf waldur-homeport-${CI_COMMIT_TAG}-source.cyclonedx.tar.gz waldur-homeport-${CI_COMMIT_TAG}-source.cyclonedx.json
    - echo "SBOM archived. Size:"
    - du -h waldur-homeport-${CI_COMMIT_TAG}-source.cyclonedx.tar.gz
  artifacts:
    paths:
      - waldur-homeport-${CI_COMMIT_TAG}-source.cyclonedx.tar.gz

Upload translatable strings:
  stage: build
  interruptible: true
  rules:
    - if: '$SKIP_I18N_UPLOAD == "true" || $SKIP_I18N_UPLOAD == "yes"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop"'
      allow_failure: true
  image:
    name: registry.hpc.ut.ee/mirror/localazy/cli:latest
  script:
    - sed 's/{\([^}]*\)\}/{__\1__}/g' template.json > template-for-localazy.json
    - localazy upload source -w $LOCALAZY_WRITE_KEY -r $LOCALAZY_READ_KEY
  before_script: []

Download translation:
  stage: test
  interruptible: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop" && $CI_PIPELINE_SOURCE == "schedule"'
  image:
    name: registry.hpc.ut.ee/mirror/localazy/cli:latest
  script:
    - apt update && apt install -y git jq
    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git remote set-url origin "https://gitlab-ci-token:${GITLAB_TOKEN}@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    - git fetch origin develop
    - git branch -D new-translations || echo "No translation branch" # cleanup
    - localazy download -w $LOCALAZY_WRITE_KEY -r $LOCALAZY_READ_KEY
    - find locales -type f -name '*.json' -exec sed -i 's/{__\([^}]*\)__\}/{\1}/g' {} \;
    - |
      for file in locales/*.json; do
        echo $file
        if [[ $file == "locales/en.json" ]]; then
          continue
        fi
        jq 'to_entries | map({(.key): .value.message}) | add' "$file" > temp.json  && mv temp.json "$file"
      done
    - rm -f temp.json
    - git status
    - git add locales/*
    - git commit locales -m "Updates translations" || exit 0
    - git status
    - echo "Committing updated translations"
    - git branch new-translations
    - git push --set-upstream origin new-translations:develop
  before_script: []

Update UI developer docs:
  stage: build
  interruptible: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  image:
    name: registry.hpc.ut.ee/mirror/alpine/git:latest
    entrypoint: [""]
  script:
    - cd /tmp/
    - git clone "https://homeport-token:$DOCS_TOKEN@$CI_SERVER_HOST/waldur/waldur-docs.git"
    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - cd waldur-docs
    - cp -rv $CI_PROJECT_DIR/docs/* docs/developer-guide/ui
    - git add docs/developer-guide/ui
    - git commit -m "Update UI developer docs" || exit 0
    - git branch new-ui-guide
    - git push --set-upstream origin new-ui-guide:master
  before_script: []

Build test docker image:
  stage: test
  interruptible: true
  image:
    name: "gcr.io/kaniko-project/executor:debug"
    entrypoint: [""]
  rules:
    - if: '$SKIP_TESTS == "true" || $SKIP_TESTS == "yes"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  before_script:
    - echo "[+] Build and publish docker image for merge request ${CI_MERGE_REQUEST_ID}"
    - mkdir build-info
    - echo $CI_COMMIT_SHA > build-info/COMMIT_SHA
  script:
    - echo $CI_REGISTRY_IMAGE:$CI_MERGE_REQUEST_ID
    - AUTH=$(echo -n "${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}" | base64)
    - |
      cat << EOF > /kaniko/.docker/config.json
      {
        "auths": {
          "https://${CI_REGISTRY}": {
            "auth": "${AUTH}"
          }
        }
      }
      EOF
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --registry-map docker.io=registry.hpc.ut.ee/mirror
      --registry-map index.docker.io=registry.hpc.ut.ee/mirror
      --build-arg="DOCKER_REGISTRY=${DOCKER_REGISTRY}"
      --build-arg="ASSET_PATH=/${CI_MERGE_REQUEST_ID}/"
      --destination "${CI_REGISTRY_IMAGE}:${CI_MERGE_REQUEST_ID}"

Test k8s deployment:
  stage: validate
  image:
    name: "registry.hpc.ut.ee/mirror/bitnami/kubectl:1.29.4-debian-12-r2"
    entrypoint: ['']
  interruptible: false
  environment:
    name: test-${CI_MERGE_REQUEST_ID}
    action: start
    on_stop: Cleanup test k8s deployment
    url: https://homeport-testing.waldur.com/${CI_MERGE_REQUEST_ID}/
  rules:
    - if: '$SKIP_TESTS == "true" || $SKIP_TESTS == "yes"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  before_script:
    - export KUBECONFIG=${K8S_CONFIG_WALDUR_HELM_TEST}
    - apt update && apt install gettext -y
  script:
    - kubectl config current-context
    - envsubst < k8s-test/deployment-tpl.yaml > k8s-test/deployment.yaml
    - envsubst < k8s-test/service-tpl.yaml > k8s-test/service.yaml
    - envsubst < k8s-test/ingress-tpl.yaml > k8s-test/ingress.yaml
    - kubectl delete secret waldur-homeport-test-${CI_MERGE_REQUEST_ID} || true
    - kubectl create secret docker-registry waldur-homeport-test-${CI_MERGE_REQUEST_ID} --docker-server=${CI_REGISTRY} --docker-username=${CI_REGISTRY_USER} --docker-password=${CI_REGISTRY_PASSWORD}
    - kubectl apply -f k8s-test/deployment.yaml --wait
    - kubectl apply -f k8s-test/service.yaml
    - kubectl apply -f k8s-test/ingress.yaml
    - kubectl rollout restart deployment waldur-homeport-test-${CI_MERGE_REQUEST_ID}
    # Wait for rollout completion
    - kubectl rollout status deployment waldur-homeport-test-${CI_MERGE_REQUEST_ID} --timeout 120s
    # Wait a bit more to avoid race conditions
    - sleep 5
    - kubectl get pods -l app=waldur-homeport-test-${CI_MERGE_REQUEST_ID} --field-selector=status.phase=Running
    - POD_NAME=$(kubectl get pod -l app=waldur-homeport-test-${CI_MERGE_REQUEST_ID} --sort-by=.metadata.creationTimestamp -o name | tail -n1)
    - echo $POD_NAME
    # Wait until the pod is ready to ensure the image is pulled
    - kubectl wait --timeout=180s --for=condition=Ready=true $POD_NAME
    - kubectl get pods -l app=waldur-homeport-test-${CI_MERGE_REQUEST_ID}
  allow_failure: true

Upload Image SBOM:
  extends: .Upload SBOM template
  needs:
    - Generate Image SBOM
  variables:
    PROJECT_NAME: "waldur-homeport"
    SBOM_TYPE: "image"
    SBOM_DIR: "images"

Upload Source SBOM:
  extends: .Upload SBOM template
  needs:
    - Generate Codebase SBOM
  variables:
    PROJECT_NAME: "waldur-homeport"
    SBOM_TYPE: "source"
    SBOM_DIR: "source"

Cleanup test k8s deployment:
  stage: deploy
  image:
    name: "registry.hpc.ut.ee/mirror/bitnami/kubectl:1.29.4-debian-12-r2"
    entrypoint: ['']
  interruptible: false
  rules:
  - if: '$SKIP_TESTS == "true" || $SKIP_TESTS == "yes"'
    when: never
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    when: manual
  environment:
    name: test-${CI_MERGE_REQUEST_ID}
    action: stop
  before_script:
    - export KUBECONFIG=${K8S_CONFIG_WALDUR_HELM_TEST}
  script:
    - kubectl delete secret waldur-homeport-test-${CI_MERGE_REQUEST_ID} || true
    - kubectl delete deployment waldur-homeport-test-${CI_MERGE_REQUEST_ID} || true
    - kubectl delete service waldur-homeport-test-${CI_MERGE_REQUEST_ID} || true
    - kubectl delete ingress waldur-homeport-test-${CI_MERGE_REQUEST_ID} || true

Cleanup previous k8s test deployment:
  extends: Cleanup test k8s deployment
  stage: .pre
  rules:
  - if: '$SKIP_TESTS == "true" || $SKIP_TESTS == "yes"'
    when: never
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
