overrides:
  customers:
    filters:
      - accounting_is_running
      - is_service_provider
      - is_call_managing_organization
      - organization_group_uuid
    is_service_provider:
      label: Service provider
    is_call_managing_organization:
      label: Call managing organization
      feature: show_call_management_functionality
    accounting_is_running:
      label: Accounting is running
      placeholder: 'Show with running accounting'
      enumOverrides:
        'undefined': All
        'true': Running accounting
        'false': Not running accounting

  financial_reports:
    filters:
      - customer_uuid
      - accounting_period
      - accounting_is_running
    customer_uuid:
      label: Service provider
      operationId: marketplace_service_providers_list
      valueField: customer_uuid
      labelField: customer_name
    accounting_period:
      label: Accounting period
      options: props.accountingPeriods
      mapTo: true
    accounting_is_running:
      label: Accounting is running
      placeholder: 'Show with running accounting'
      enumOverrides:
        true: Running accounting
        false: Not running accounting
        undefined: All

  marketplace_resources:
    filters:
      - customer_uuid
      - project_uuid
    customer_uuid:
      label: Organization
      name: organization
    project_uuid:
      name: project
      extraQuery:
        customer: 'props.organizationUuid'

  admin_arrow_consumption_records:
    filters:
      - customer_uuid
      - is_finalized
    customer_uuid:
      label: Organization
      name: organization
    is_finalized:
      label: Status
      enumOverrides:
        true: Finalized
        false: Pending

  openstack_images:
    filters:
      - show_duplicate_names
    show_duplicate_names:
      label: Show duplicate names
      component: AwesomeCheckboxField
      badgeLabels:
        true: Yes
        false: No

  invoices_items:
    operationId: invoices_items_retrieve
    filters:
      - provider_uuid
      - project_uuid
      - offering_uuid
      - conceal_compensation_items
    provider_uuid:
      label: Service provider
      name: provider
      operationId: marketplace_service_providers_list
    project_uuid:
      name: project
      operationId: projects_list
      extraQuery:
        customer: 'props.customerUuid'
    offering_uuid:
      name: offering
      operationId: marketplace_public_offerings_list
      extraQuery:
        state: ['Active']
    conceal_compensation_items:
      component: AwesomeCheckboxField

  email_logs:
    filters:
      - emails
      - subject
      - sent_at
    emails:
      placeholder: 'Emails contains'
    subject:
      placeholder: 'Subject contains'
    sent_at:
      placeholder: 'YYYY-MM-DD'

  user_invitations:
    filters:
      - state
      - role_uuid
      - customer_uuid
      - scope_type
    state:
      label: State
      enumOverrides:
        requested: Requested
        rejected: Rejected
        pending: Pending
        project: Pending project start
        canceled: Canceled
        expired: Expired
        accepted: Accepted
    customer_uuid:
      label: Organization
    role_uuid:
      labelField: description
    scope_type:
      label: Scope type
      enumOverrides:
        customer: Organization
        project: Project
        offering: Offering
        call: Call
        proposal: Proposal
        service_provider: Service provider organization
        call_organizer: Call managing organization

  projects_list_users:
    filters:
      - project_role
    project_role:
      label: Role
      mapTo: role
      options: props.projectRoles
      valueField: name
      labelField: description

  customers_users:
    filters:
      - project_role
      - organization_role
    project_role:
      isMulti: true
      options: props.projectRoles
      valueField: name
      labelField: description
    organization_role:
      isMulti: true
      options: props.organizationRoles
      valueField: name
      labelField: description

  marketplace_project_update_requests:
    filters:
      - state

  notification_messages:
    filters:
      - is_overridden
    is_overridden:
      label: Status
      enumOverrides:
        'false': Not overridden
        'true': Overridden

  broadcast_messages:
    filters:
      - state

  admin_announcements:
    filters:
      - type
      - is_active
    is_active:
      label: Status
      enumOverrides:
        'true': Active
        'false': Inactive

  support_feedbacks:
    filters:
      - evaluation
      - user_uuid
      - period
    evaluation:
      label: Evaluation
      options: props.evaluationOptions
    period:
      label: Period
      options: props.periodOptions
      mapTo: true

  data_access_logs:
    filters:
      - start_date
      - end_date
      - accessor_type
      - user_uuid
    user_uuid:
      searchParam: full_name
      extraQuery:
        o: ['full_name']

  customer_quotas:
    initialValues:
      quota_name: { label: Resources, value: estimated_price }
    filters:
      - quota_name
    quota_name:
      label: Quota

  openportal_managed_projects:
    filters:
      - state

  marketplace_plan_components:
    filters:
      - offering_uuid
    offering_uuid:
      searchParam: name

  marketplace_plans_usage_stats:
    filters:
      - customer_provider_uuid
      - offering_uuid
    customer_provider_uuid:
      label: Service provider
      name: provider
      operationId: marketplace_service_providers_list
      labelField: customer_name
      valueField: customer_uuid
    offering_uuid:
      searchParam: name

  admin_arrow_billing_syncs:
    filters:
      - state
      - report_period_from
      - report_period_to
    state:
      label: State
      options:
        - label: Pending
          value: 1
        - label: Syncing
          value: 2
        - label: Synced
          value: 3
        - label: Failed
          value: 4
    report_period_from:
      label: Period from
      options: 'props.billingPeriods'
    report_period_to:
      label: Period to
      options: 'props.billingPeriods'

  admin_arrow_customer_mappings:
    filters:
      - waldur_customer_uuid
      - arrow_reference
      - is_active
    waldur_customer_uuid:
      label: Waldur Organization
      name: organization
    arrow_reference:
      label: Arrow Reference
    is_active:
      label: Active

  marketplace_customer_estimated_cost_policies:
    filters:
      - customer_uuid
    customer_uuid:
      label: Organization
      name: organization

  chat_threads:
    filters:
      - created
      - modified
      - user
      - is_flagged
      - max_severity
      - is_archived
    user:
      searchParam: full_name

  events:
    filters:
      - customer_uuid
      - project_uuid
      - user_uuid
      - feature
    customer_uuid:
      label: Organization
      name: organization
    project_uuid:
      name: project
    user_uuid:
      label: User
      name: user
      searchParam: full_name
      extraQuery:
        o: ['full_name']
    feature:
      label: Type
      isMulti: true
      enumOverrides:
        projects: Project events
        resources: Resource events

  system_logs:
    filters:
      - source
      - level
      - instance
      - logger_name
      - start_date
      - end_date
    start_date:
      component: DateField
      mapTo: false
    end_date:
      component: DateField
      mapTo: false

  marketplace_robot_accounts:
    filters:
      - customer_uuid
      - project_uuid
    customer_uuid:
      label: Organization
      name: customer
      operationId: marketplace_service_providers_robot_account_customers_list
      searchParam: customer_name
      extraPath:
        uuid: props.provider.uuid
    project_uuid:
      name: project
      operationId: marketplace_service_providers_robot_account_projects_list
      searchParam: project_name
      extraPath:
        uuid: props.provider.uuid

  reviewer_suggestions:
    filters:
      - status
    status:
      enumOverrides:
        pending: Pending
        confirmed: Confirmed
        rejected: Rejected
        invited: Invited

  customer_events:
    operationId: events_list
    initialValues:
      feature:
        - label: Organization events
          value: customers
    filters:
      - feature
    feature:
      label: Type
      isMulti: true
      enumOverrides:
        customers: Organization events
        projects: Project events
        resources: Resource events

  user_group_invitations:
    filters:
      - is_active
    is_active:
      label: Group invitations
      component: AwesomeCheckboxField
      badgeLabels:
        true: Only active
        false: All

  invoices:
    filters:
      - state
    state:
      isMulti: true
      enumOverrides:
        pending: Pending
        pending_finalization: Pending finalization
        canceled: Canceled
        created: Created
        paid: Paid

  marketplace_provider_offerings:
    initialValues:
      state:
        - label: Draft
          value: Draft
        - label: Active
          value: Active
    filters:
      - state
    state:
      isMulti: true
      enumOverrides:
        Draft: Draft
        Active: Active
        Paused: Paused
        Archived: Archived
        Unavailable: Unavailable

  project_resources:
    operationId: marketplace_resources_list
    filters:
      - offering_uuid
    offering_uuid:
      operationId: marketplace_public_offerings_list
      extraQuery:
        project_uuid: 'props.project.uuid'

  proposal_proposals:
    initialValues:
      state:
        - label: Submitted
          value: submitted
        - label: Accepted
          value: accepted
        - label: In review
          value: in_review
    filters:
      - state
      - call_uuid
      - round_uuid
      - organization_uuid
    state:
      isMulti: true
      enumOverrides:
        draft: Draft
        submitted: Submitted
        accepted: Accepted
        rejected: Rejected
        canceled: Canceled
        in_review: In review
    call_uuid:
      operationId: proposal_public_calls_list
    round_uuid:
      operationId: call_rounds_list
      searchParam: false
    organization_uuid:
      label: Organization

  proposal_public_calls:
    initialValues:
      state:
        - label: Active
          value: active
      has_active_round: false
    filters:
      - state
      - has_active_round
    state:
      isMulti: true
      enumOverrides:
        draft: Draft
        active: Active
        archived: Archived
    has_active_round:
      label: Active round
      component: AwesomeCheckboxField
      badgeLabels:
        true: Yes
        false: All

  proposal_reviews:
    filters:
      - state
      - call_uuid
    state:
      isMulti: true
      enumOverrides:
        in_review: In review
        submitted: Submitted
        rejected: Rejected
    call_uuid:
      operationId: proposal_public_calls_list

  rancher_cluster:
    operationId: rancher_ingresses_list
    filters:
      - namespace_uuid
      - rancher_project_uuid
    namespace_uuid:
      extraQuery:
        cluster_uuid: 'props.cluster.uuid'
    rancher_project_uuid:
      extraQuery:
        cluster_uuid: 'props.cluster.uuid'

  invoice_items:
    filters:
      - customer_uuid
      - accounting_period
      - project_uuid
      - offering_uuid
    customer_uuid:
      label: Organization
      name: organization
    accounting_period:
      label: Period
      options: props.accountingPeriods
      mapTo: true
    project_uuid:
      name: project
    offering_uuid:
      name: offering
      operationId: marketplace_provider_offerings_list

    status:
      enumOverrides:
        Closed: Closed
        Open: Open
        Resolved: Resolved
        'Waiting for support': 'Waiting for support'

  support_issues:
    filters:
      - status
    status:
      enumOverrides:
        Closed: Closed
        Open: Open
        Resolved: Resolved
        'Waiting for support': Waiting for support
