overrides:
  customers_list:
    filters:
      - accounting_is_running
      - is_service_provider
      - is_call_managing_organization
      - organization_group_uuid
    is_service_provider:
      label: Service provider
    is_call_managing_organization:
      label: Call managing organization
      feature: show_call_management_functionality
    accounting_is_running:
      label: Accounting is running
      placeholder: 'Show with running accounting'
      enumOverrides:
        'undefined': All
        'true': Running accounting
        'false': Not running accounting

  financial_reports_list:
    filters:
      - customer_uuid
      - accounting_period
      - accounting_is_running
    customer_uuid:
      label: Service provider
      operationId: marketplace_service_providers_list
      valueField: customer_uuid
      labelField: customer_name
    accounting_period:
      label: Accounting period
      options: props.accountingPeriods
      mapTo: true
    accounting_is_running:
      label: Accounting is running
      placeholder: 'Show with running accounting'
      enumOverrides:
        true: Running accounting
        false: Not running accounting
        undefined: All

  invoices_items_retrieve:
    filters:
      - provider_uuid
      - project_uuid
      - offering_uuid
      - conceal_compensation_items
    provider_uuid:
      label: Service provider
      operationId: marketplace_service_providers_list
    offering_uuid:
      extraQuery:
        state: [Active]
    project_uuid:
      label: Project
      extraQuery:
        customer: 'props.customerUuid'

  email_logs_list:
    componentName: SupportEmailLogsFilter
    filters:
      - emails
      - subject
      - sent_at
    emails:
      placeholder: 'Emails contains'
    subject:
      placeholder: 'Subject contains'
    sent_at:
      placeholder: 'YYYY-MM-DD'

  user_invitations_list:
    filters:
      - state
      - role_uuid
      - customer_uuid
      - scope_type
    state:
      label: State
      enumOverrides:
        requested: Requested
        rejected: Rejected
        pending: Pending
        project: Pending project start
        canceled: Canceled
        expired: Expired
        accepted: Accepted
    customer_uuid:
      label: Organization
    role_uuid:
      labelField: description
    scope_type:
      label: Scope type
      enumOverrides:
        customer: Organization
        project: Project
        offering: Offering
        call: Call
        proposal: Proposal
        service_provider: Service provider organization
        call_organizer: Call managing organization

  projects_list_users_list:
    filters:
      - project_role
    project_role:
      label: Role
      mapTo: role
      options: props.projectRoles
      valueField: name
      labelField: description

  customers_users_list:
    filters:
      - project_role
      - organization_role
    project_role:
      isMulti: true
      options: props.projectRoles
      valueField: name
      labelField: description
    organization_role:
      isMulti: true
      options: props.organizationRoles
      valueField: name
      labelField: description

  marketplace_project_update_requests_list:
    componentName: ProjectUpdateRequestListFilter
    filters:
      - state

  notification_messages_list:
    filters:
      - is_overridden
    is_overridden:
      label: Status
      enumOverrides:
        'false': Not overridden
        'true': Overridden

  broadcast_messages_list:
    filters:
      - state

  admin_announcements_list:
    filters:
      - type
      - is_active
    is_active:
      label: Status
      enumOverrides:
        'true': Active
        'false': Inactive

  support_feedbacks_list:
    componentName: SupportFeedbacksFilter
    filters:
      - evaluation
      - user_uuid
      - period
    evaluation:
      label: Evaluation
      options: props.evaluationOptions
    period:
      label: Period
      options: props.periodOptions
      mapTo: true

  data_access_logs_list:
    componentName: SupportDataAccessLogsFilter
    output: './src/table/generated/SupportDataAccessLogsFilter.tsx'
    filters:
      - start_date
      - end_date
      - accessor_type
      - user_uuid
    user_uuid:
      searchParam: full_name
      extraQuery:
        o: ['full_name']

  marketplace_plan_components_list:
    componentName: PriceListFilter
    output: './src/table/generated/PriceListFilter.tsx'
    filters:
      - offering_uuid
    offering_uuid:
      searchParam: name

  marketplace_plans_usage_stats_list:
    componentName: PlanUsageFilter
    output: './src/table/generated/PlanUsageFilter.tsx'
    filters:
      - customer_provider_uuid
      - offering_uuid
    customer_provider_uuid:
      label: Service provider
      name: provider
      operationId: marketplace_service_providers_list
      labelField: customer_name
      valueField: customer_uuid
    offering_uuid:
      searchParam: name

  admin_arrow_billing_syncs_list:
    componentName: BillingSyncFilter
    output: './src/table/generated/BillingSyncFilter.tsx'
    filters:
      - state
      - report_period_from
      - report_period_to
    state:
      label: State
      options:
        - label: Pending
          value: 1
        - label: Syncing
          value: 2
        - label: Synced
          value: 3
        - label: Failed
          value: 4
    report_period_from:
      label: Period from
      options: 'props.billingPeriods'
    report_period_to:
      label: Period to
      options: 'props.billingPeriods'

  admin_arrow_customer_mappings_list:
    componentName: CustomerMappingsFilter
    output: './src/table/generated/CustomerMappingsFilter.tsx'
    filters:
      - waldur_customer_uuid
      - arrow_reference
      - is_active
    waldur_customer_uuid:
      label: Waldur Organization
      name: organization
    arrow_reference:
      label: Arrow Reference
    is_active:
      label: Active

  marketplace_customer_estimated_cost_policies_list:
    componentName: OrganizationCostPoliciesFilter
    output: './src/table/generated/OrganizationCostPoliciesFilter.tsx'
    filters:
      - customer_uuid
    customer_uuid:
      label: Organization
      name: organization

  chat_threads_list:
    componentName: SupportAIAssistantLogsFilter
    output: './src/table/generated/SupportAIAssistantLogsFilter.tsx'
    filters:
      - created
      - modified
      - user
      - is_flagged
      - max_severity
      - is_archived
    user:
      searchParam: full_name

  system_logs_list:
    componentName: SupportSystemLogsFilter
    output: './src/table/generated/SupportSystemLogsFilter.tsx'
    filters:
      - source
      - level
      - instance
      - logger_name
      - start_date
      - end_date
    start_date:
      component: DateField
      mapTo: false
    end_date:
      component: DateField
      mapTo: false

  marketplace_robot_accounts_list:
    componentName: ProviderRobotAccountFilter
    output: './src/table/generated/ProviderRobotAccountFilter.tsx'
    filters:
      - customer_uuid
      - project_uuid
    customer_uuid:
      label: Organization
      name: customer
      operationId: marketplace_service_providers_robot_account_customers_list
      searchParam: customer_name
      extraPath:
        uuid: props.provider.uuid
    project_uuid:
      name: project
      operationId: marketplace_service_providers_robot_account_projects_list
      searchParam: project_name
      extraPath:
        uuid: props.provider.uuid
