import {
  ComposerPrimitive,
  ThreadPrimitive,
  useAssistantState,
} from '@assistant-ui/react';
import {
  MagnifyingGlassIcon,
  PaperPlaneTiltIcon,
  StopIcon,
} from '@phosphor-icons/react';
import classNames from 'classnames';
import { FC, ReactNode } from 'react';

import { AlertItem } from '@/core/AlertItem';
import { translate } from '@/i18n';

interface Props {
  placeholder: string;
  // Rendered before Send/Stop in the action row (e.g. the token-usage toggle).
  // When present, Send/Stop flow after it instead of being right-aligned.
  leadingActions?: ReactNode;
  // Rendered between the input and the action row (e.g. a token usage summary).
  usageRow?: ReactNode;
}

// Shared assistant composer: the AI reminder (empty state), the search-style
// input, the Send/Stop buttons, and the disclaimer (once a conversation
// starts). Callers slot in any extra actions (e.g. token usage).
export const AssistantComposer: FC<Props> = ({
  placeholder,
  leadingActions,
  usageRow,
}) => {
  const isEmpty = useAssistantState(
    ({ thread }) => thread.messages.length === 0,
  );
  // With no leading actions, right-align Send/Stop so they don't hug the input.
  const alignEnd = !leadingActions;

  return (
    <div className="aui-composer-wrapper">
      {isEmpty && (
        <AlertItem
          variant="info"
          type="floating"
          title={translate('Reminder')}
          body={translate(
            'Responses are generated by AI and may be inaccurate. Never share sensitive credentials (API keys, passwords, SSH keys). Verify suggestions before acting.',
          )}
        />
      )}
      <ComposerPrimitive.Root className="aui-composer-root">
        <div className="aui-composer-input-row">
          <MagnifyingGlassIcon weight="bold" />
          <ComposerPrimitive.Input
            placeholder={placeholder}
            className="aui-composer-input"
            rows={1}
            autoFocus
            aria-label={translate('Message input')}
          />
        </div>
        {usageRow}
        <div className="aui-composer-action-row">
          <div className="aui-composer-action-wrapper">
            {leadingActions}
            <ThreadPrimitive.If running={false}>
              <ComposerPrimitive.Send asChild>
                {/* asChild requires a raw <button> here, not the design-token Button */}
                <button
                  className={classNames(
                    'btn btn-text-primary btn-sm d-flex align-items-center gap-2',
                    alignEnd && 'ms-auto',
                  )}
                  aria-label={translate('Send message')}
                >
                  <PaperPlaneTiltIcon weight="bold" />
                  <span>{translate('Send')}</span>
                </button>
              </ComposerPrimitive.Send>
            </ThreadPrimitive.If>
            <ThreadPrimitive.If running>
              <ComposerPrimitive.Cancel asChild>
                <button
                  type="button"
                  className={classNames(
                    'aui-composer-cancel-button',
                    alignEnd && 'ms-auto',
                  )}
                  aria-label={translate('Stop generating')}
                >
                  <StopIcon weight="bold" />
                </button>
              </ComposerPrimitive.Cancel>
            </ThreadPrimitive.If>
          </div>
        </div>
      </ComposerPrimitive.Root>
      {!isEmpty && (
        <p className="text-muted fs-8 text-center mb-0 mt-1">
          {translate(
            'AI may produce inaccurate responses. Do not share sensitive credentials.',
          )}
        </p>
      )}
    </div>
  );
};
