#!/usr/bin/env node
/**
 * Generates the colour ramps for both consumers from one source:
 *
 *   packages/design-tokens/tokens/colors.json
 *     -> src/metronic/sass/_color-ramps.scss        (Bootstrap/Metronic, SCSS)
 *     -> packages/design-tokens/src/colorRamps.css  (Tailwind + CSS variables)
 *
 * Usage:
 *   node packages/design-tokens/scripts/generate-tokens.mjs           write files
 *   node packages/design-tokens/scripts/generate-tokens.mjs --check   exit 1 if stale
 *
 * The two outputs used to be hand-maintained copies and drifted. Plain node,
 * no dependencies: the transform is small, and Style Dictionary can't emit
 * `if(isDarkMode(), dark, light)` without a custom format anyway.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
export const repoRoot = path.resolve(here, '../../..');

export const TOKENS_FILE = path.join(
  repoRoot,
  'packages/design-tokens/tokens/colors.json',
);
export const SCSS_OUT = path.join(
  repoRoot,
  'src/metronic/sass/_color-ramps.scss',
);
export const CSS_OUT = path.join(
  repoRoot,
  'packages/design-tokens/src/colorRamps.css',
);

const SOURCE = 'packages/design-tokens/tokens/colors.json';
const GENERATOR = 'packages/design-tokens/scripts/generate-tokens.mjs';

const numeric = (a, b) => Number(a) - Number(b);

/** Steps of a ramp in numeric order, with defaults applied. */
const stepsOf = (name, ramp) =>
  Object.keys(ramp.steps)
    .sort(numeric)
    .map((step) => {
      const { light, dark, scss } = ramp.steps[step];
      if (
        !/^#[0-9a-f]{6}$/.test(light) ||
        (dark !== undefined && !/^#[0-9a-f]{6}$/.test(dark))
      ) {
        throw new Error(`${name}-${step}: colours must be lower-case #rrggbb`);
      }
      if (dark === light) {
        throw new Error(`${name}-${step}: drop "dark" when it equals "light"`);
      }
      return { step, light, dark, scss: scss !== false };
    });

const wrap = (text, prefix, width = 76) => {
  const lines = [];
  let line = prefix;
  for (const word of text.split(/\s+/)) {
    if (
      line.length + word.length + 1 > width &&
      line.trim() !== prefix.trim()
    ) {
      lines.push(line);
      line = prefix + word;
    } else {
      line += (line === prefix ? '' : ' ') + word;
    }
  }
  lines.push(line);
  return lines.join('\n');
};

export function generateScss(tokens) {
  const out = [
    `// GENERATED by ${GENERATOR}`,
    `// from ${SOURCE} — do not edit by hand; edit the JSON and run \`yarn tokens:generate\`.`,
    '//',
    '// Every step is resolved at compile time: `if(isDarkMode(), dark, light)` for a',
    '// step with its own dark value, a plain hex when it is the same in both themes.',
    '// Derived variables ($success, $success-active, ...) stay in _colors.scss.',
  ];
  for (const [key, ramp] of Object.entries(tokens.ramps)) {
    if (ramp.scss === false) continue;
    const name = ramp.scssName ?? key;
    const flag = ramp.scssDefault === false ? '' : ' !default';
    const lines = stepsOf(key, ramp)
      .filter((s) => s.scss)
      .map(({ step, light, dark }) =>
        dark === undefined
          ? `$${name}-${step}: ${light}${flag};`
          : `$${name}-${step}: if(isDarkMode(), ${dark}, ${light})${flag};`,
      );
    out.push('', `// ${name}`);
    if (ramp.description) out.push(wrap(ramp.description, '// '));
    out.push(...lines);
  }
  return out.join('\n') + '\n';
}

export function generateCss(tokens) {
  const out = [
    '/**',
    ` * GENERATED by ${GENERATOR}`,
    ` * from ${SOURCE} — do not edit by hand; edit the JSON and run \`yarn tokens:generate\`.`,
    ' *',
    ' * Declared once, in `@theme static`, under the names Tailwind itself uses',
    ' * (--color-<ramp>-<step>): that registers the bg-, text- and border-',
    ' * utilities and provides the `var(--color-gray-50)` the sibling token files',
    ' * read. Every ramp is physical (step 900 is dark in both themes); the dark',
    ' * theme is chosen by the semantic tokens, which read `gray-dark` there.',
    ' */',
    '',
    '@theme static {',
  ];
  const blocks = [];
  for (const [key, ramp] of Object.entries(tokens.ramps)) {
    if (ramp.css === false) continue;
    const lines = [];
    if (ramp.description || ramp.note) {
      const text = [ramp.description, ramp.note].filter(Boolean).join(' ');
      const wrapped = wrap(text, '     ', 78).split('\n');
      wrapped[0] = '  /* ' + wrapped[0].slice(5);
      wrapped[wrapped.length - 1] += ' */';
      lines.push(...wrapped);
    }
    for (const { step, light } of stepsOf(key, ramp)) {
      lines.push(`  --color-${key}-${step}: ${light};`);
    }
    blocks.push(lines.join('\n'));
  }
  out.push(blocks.join('\n\n'), '}', '');

  return out.join('\n');
}

export const readTokens = () => JSON.parse(readFileSync(TOKENS_FILE, 'utf8'));

/** { absolutePath: content } for every generated file. */
export const generateAll = (tokens = readTokens()) => ({
  [SCSS_OUT]: generateScss(tokens),
  [CSS_OUT]: generateCss(tokens),
});

const isCli =
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isCli) {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const [file, content] of Object.entries(generateAll())) {
    const rel = path.relative(repoRoot, file);
    if (check) {
      if (!existsSync(file) || readFileSync(file, 'utf8') !== content) {
        console.error(`stale: ${rel} — run \`yarn tokens:generate\``);
        stale += 1;
      }
    } else {
      writeFileSync(file, content);
      console.log(`wrote ${rel}`);
    }
  }
  process.exit(stale ? 1 : 0);
}
