import userEvents from './user-events';
import userManage from './user-manage';
import userSidebar from './user-sidebar';
import userDetails from './user-details';
import { userEdit } from './user-edit';
import userDashboard from './user-dashboard';
import userOrganizations from './user-organizations';
import userProjects from './user-projects';
import { userPopover } from './user-popover';
import userPopoverTable from './user-popover-table';
import { stateUtilsService, attachStateUtils } from './utils';
import userRoutes from './routes';
import usersService from './users-service';
import userToken from './user-token';
import filtersModule from './filters';
import hooksModule from './hooks/module';
import keysModule from './keys/module';

export default module => {
  module.directive('userEvents', userEvents);
  module.component('userManage', userManage);
  module.component('userSidebar', userSidebar);
  module.directive('userDetails', userDetails);
  module.component('userEdit', userEdit);
  module.component('userDashboard', userDashboard);
  module.component('userOrganizations', userOrganizations);
  module.component('userProjects', userProjects);
  module.component('userPopover', userPopover);
  module.component('userPopoverTable', userPopoverTable);
  module.service('stateUtilsService', stateUtilsService);
  module.service('usersService', usersService);
  module.run(attachStateUtils);
  module.config(userRoutes);
  module.component('userToken', userToken);
  filtersModule(module);
  hooksModule(module);
  keysModule(module);
};
