export const JUPYTER_HUB_MANAGEMENT_LOADED = 'waldur/jupyterHubManagement/JUPYTER_HUB_MANAGEMENT_LOADED';
export const JUPYTER_HUB_MANAGEMENT_ERRED = 'waldur/jupyterHubManagement/JUPYTER_HUB_MANAGEMENT_ERRED';
export const SAVE_AVAILABLE_PYTHON_MANAGEMENTS = 'waldur/jupyterHubManagement/SAVE_AVAILABLE_PYTHON_MANAGEMENTS';
