import issuesService from './issues-service';
import IssueTypesService from './issue-types-service';
import IssueNavigationService from './issue-navigation-service';
import { attachStateUtils } from './issue-navigation-service';
import issueUsersService from './issue-users';
import issueDetail from './issue-detail';
import issuesList from './issues-list';
import issueRoutes from './routes';
import issuesWorkspace from './issues-workspace';
import { issuesDashboard } from './issues-dashboard';
import { issuesShortList } from './issues-short-list';
import issueQuickCreate from './issue-quick-create';
import issuesActivityStream from './issues-activity-stream';
import issuesListFiltered from './issues-list-filtered';
import issuesHelpdesk from './issues-helpdesk';
import issueCreateDialog from './issue-create-dialog';
import issueRegistration from './issue-registration';
import {ISSUE_IDS} from './constants';
import issueTypeSelect from './issue-type-select';
import issueCommentsModule from './comments/module';
import requestServiceButton from './request-service-button';
import registerExtensionPoint from './extend-appstore-selector';

export default module => {
  module.constant('ISSUE_IDS', ISSUE_IDS);
  module.service('issuesService', issuesService);
  module.service('IssueTypesService', IssueTypesService);
  module.service('IssueNavigationService', IssueNavigationService);
  module.run(attachStateUtils);
  module.service('issueUsersService', issueUsersService);
  module.component('issuesList', issuesList);
  module.component('issueDetail', issueDetail);
  module.component('issuesWorkspace', issuesWorkspace);
  module.component('issuesDashboard', issuesDashboard);
  module.component('issuesShortList', issuesShortList);
  module.directive('issueQuickCreate', issueQuickCreate);
  module.directive('issuesActivityStream', issuesActivityStream);
  module.component('issuesListFiltered', issuesListFiltered);
  module.directive('issuesHelpdesk', issuesHelpdesk);
  module.component('issueCreateDialog', issueCreateDialog);
  module.directive('issueRegistration', issueRegistration);
  module.component('issueTypeSelect', issueTypeSelect);
  module.component('requestServiceButton', requestServiceButton);
  module.config(issueRoutes);
  module.run(registerExtensionPoint);
  issueCommentsModule(module);
};
