import customerManage from './customer-manage';
import customerWorkspace from './customer-workspace';
import { CustomerWorkspaceController } from './customer-workspace';
import { customerPopover } from './customer-popover';
import customerAlerts from './customer-alerts';
import customerIssues from './customer-issues';
import customerEvents from './customer-events';
import {customerUsersDetailsList} from './customer-users-details-list';
import customerTeam from './customer-team';
import PriceEstimatesService from './price-estimates-service';
import customerPolicies from './customer-policies';
import customerReportError from './customer-report-error';
import customerCreateDialog from './customer-create-dialog';
import customerCreatePrompt from './customer-create-prompt';
import CustomerCreateService from './customer-create-service';
import customerThreshold from './customer-threshold';
import customerCountryField from './customer-country-field';
import customerThresholdField from './customer-threshold-field';
import routes from './routes';
import attachHooks from './hooks';

export default module => {
  module.component('customerThreshold', customerThreshold);
  module.component('customerCreatePrompt', customerCreatePrompt);
  module.component('customerCreateDialog', customerCreateDialog);
  module.service('CustomerCreateService', CustomerCreateService);
  module.component('customerManage', customerManage);
  module.controller('CustomerWorkspaceController', CustomerWorkspaceController);
  module.directive('customerWorkspace', customerWorkspace);
  module.component('customerPopover', customerPopover);
  module.component('customerAlerts', customerAlerts);
  module.component('customerIssues', customerIssues);
  module.component('customerEvents', customerEvents);
  module.component('customerCountryField', customerCountryField);
  module.component('customerThresholdField', customerThresholdField);
  module.component('customerUsersDetailsList', customerUsersDetailsList);
  module.component('customerTeam', customerTeam);
  module.component('customerPolicies', customerPolicies);
  module.component('customerReportError', customerReportError);
  module.service('priceEstimatesService', PriceEstimatesService);
  module.config(routes);
  module.run(attachHooks);
};
