import { translate } from '@waldur/i18n';

export const OECD_FOS_2007_CODES = [
  { value: '1.1', label: translate('Mathematics') },
  { value: '1.2', label: translate('Computer and information sciences') },
  { value: '1.3', label: translate('Physical sciences') },
  { value: '1.4', label: translate('Chemical sciences') },
  {
    value: '1.5',
    label: translate('Earth and related environmental sciences'),
  },
  { value: '1.6', label: translate('Biological sciences') },
  { value: '1.7', label: translate('Other natural sciences') },
  { value: '2.1', label: translate('Civil engineering') },
  {
    value: '2.2',
    label: translate(
      'Electrical engineering, electronic engineering, information engineering',
    ),
  },
  { value: '2.3', label: translate('Mechanical engineering') },
  { value: '2.4', label: translate('Chemical engineering') },
  { value: '2.5', label: translate('Materials engineering') },
  { value: '2.6', label: translate('Medical engineering') },
  { value: '2.7', label: translate('Environmental engineering') },
  { value: '2.8', label: translate('Systems engineering') },
  { value: '2.9', label: translate('Environmental biotechnology') },
  { value: '2.10', label: translate('Industrial biotechnology') },
  { value: '2.11', label: translate('Nano technology') },
  { value: '2.12', label: translate('Other engineering and technologies') },
  { value: '3.1', label: translate('Basic medicine') },
  { value: '3.2', label: translate('Clinical medicine') },
  { value: '3.3', label: translate('Health sciences') },
  { value: '3.4', label: translate('Health biotechnology') },
  { value: '3.5', label: translate('Other medical sciences') },
  { value: '4.1', label: translate('Agriculture, forestry, and fisheries') },
  { value: '4.2', label: translate('Animal and dairy science') },
  { value: '4.3', label: translate('Veterinary science') },
  { value: '4.4', label: translate('Agricultural biotechnology') },
  { value: '4.5', label: translate('Other agricultural sciences') },
  { value: '5.1', label: translate('Psychology') },
  { value: '5.2', label: translate('Economics and business') },
  { value: '5.3', label: translate('Educational sciences') },
  { value: '5.4', label: translate('Sociology') },
  { value: '5.5', label: translate('Law') },
  { value: '5.6', label: translate('Political science') },
  { value: '5.7', label: translate('Social and economic geography') },
  { value: '5.8', label: translate('Media and communications') },
  { value: '5.9', label: translate('Other social sciences') },
  { value: '6.1', label: translate('History and archaeology') },
  { value: '6.2', label: translate('Languages and literature') },
  { value: '6.3', label: translate('Philosophy, ethics and religion') },
  {
    value: '6.4',
    label: translate('Arts (arts, history of arts, performing arts, music)'),
  },
  { value: '6.5', label: translate('Other humanities') },
];
