import appstoreField from './appstore-field';
import appstoreFieldBoolean from './appstore-field-boolean';
import appstoreFieldDescription from './appstore-field-description';
import appstoreFieldEmail from './appstore-field-email';
import appstoreFieldErrors from './appstore-field-errors';
import appstoreFieldFile from './appstore-field-file';
import appstoreFieldInteger from './appstore-field-integer';
import appstoreFieldLabel from './appstore-field-label';
import appstoreFieldList from './appstore-field-list';
import appstoreFieldMoney from './appstore-field-money';
import appstoreFieldMultiselect from './appstore-field-multiselect';
import appstoreFieldPassword from './appstore-field-password';
import appstoreFieldSelect from './appstore-field-select';
import appstoreFieldSelectString from './appstore-field-select-string';
import appstoreFieldString from './appstore-field-string';
import appstoreFieldTel from './appstore-field-tel';
import appstoreFieldText from './appstore-field-text';
import appstoreFieldTos from './appstore-field-tos';
import appstoreFormFieldset from './appstore-form-fieldset';
import appstoreFormWizard from './appstore-form-wizard';
import appstoreListDialog from './appstore-list-dialog';
import choicesTable from './choices-table';
import fieldLabel from './field-label';
import FormUtils from './form-utils';
import helpicon from './help-icon';
import multiplyBy from './multiply-by';

export default module => {
  module.service('formUtils', FormUtils);
  module.directive('appstoreField', appstoreField);
  module.component('appstoreFormFieldset', appstoreFormFieldset);
  module.component('appstoreFieldString', appstoreFieldString);
  module.component('appstoreFieldEmail', appstoreFieldEmail);
  module.component('appstoreFieldFile', appstoreFieldFile);
  module.component('appstoreFieldTel', appstoreFieldTel);
  module.component('appstoreFieldTos', appstoreFieldTos);
  module.directive('appstoreFieldPassword', appstoreFieldPassword);
  module.directive('appstoreFieldText', appstoreFieldText);
  module.component('appstoreFormWizard', appstoreFormWizard);
  module.component('appstoreFieldInteger', appstoreFieldInteger);
  module.component('appstoreFieldMoney', appstoreFieldMoney);
  module.component('appstoreFieldBoolean', appstoreFieldBoolean);
  module.directive('appstoreFieldErrors', appstoreFieldErrors);
  module.directive('appstoreFieldLabel', appstoreFieldLabel);
  module.directive('appstoreFieldDescription', appstoreFieldDescription);
  module.directive('appstoreFieldList', appstoreFieldList);
  module.component('appstoreFieldMultiselect', appstoreFieldMultiselect);
  module.component('appstoreFieldSelect', appstoreFieldSelect);
  module.component('appstoreFieldSelectString', appstoreFieldSelectString);
  module.directive('appstoreListDialog', appstoreListDialog);
  module.directive('fieldLabel', fieldLabel);
  module.directive('helpicon', helpicon);
  module.directive('multiplyBy', multiplyBy);
  module.directive('choicesTable', choicesTable);
};
