export const EVENT_TEMPLATES = {
  auth_logged_in_with_username: 'User {user_full_name} authenticated successfully with username and password.',
  customer_account_credited: 'Balance has been increased by {amount} for customer {customer_name}.',
  customer_account_debited: 'Balance has been decreased by {amount} for customer {customer_name}.',
  customer_creation_succeeded: 'Organization {customer_name} has been created.',
  customer_deletion_succeeded: 'Organization {customer_name} has been deleted.',
  customer_update_succeeded: 'Organization {customer_name} has been updated.',
  invoice_creation_succeeded: 'Invoice for organization {customer_name} for the period of {invoice_date} has been created.',
  invoice_deletion_succeeded: 'Invoice for organization {customer_name} for the period of {invoice_date} has been deleted.',
  invoice_update_succeeded: 'Invoice for organization {customer_name} for the period of {invoice_date} has been updated.',
  payment_approval_succeeded: 'Payment for {customer_name} has been approved',
  payment_cancel_succeeded: 'Payment for {customer_name} has been cancelled',
  payment_creation_succeeded: 'Created a new payment for {customer_name}',
  project_creation_succeeded: 'Project {project_name} has been created.',
  project_deletion_succeeded: 'Project {project_name} has been deleted.',
  project_name_update_succeeded: 'Project has been renamed from {project_previous_name} to {project_name}.',
  project_update_succeeded: 'Project {project_name} has been updated.',
  quota_threshold_reached: '{quota_name} quota threshold has been reached for project {project_name}.',
  resource_creation_failed: 'Resource {resource_name} creation has failed.',
  resource_creation_scheduled: 'Resource {resource_name} creation has been scheduled.',
  resource_creation_succeeded: 'Resource {resource_name} has been created.',
  resource_deletion_failed: 'Resource {resource_name} deletion has failed.',
  resource_deletion_scheduled: 'Resource {resource_name} has been scheduled to deletion.',
  resource_deletion_succeeded: 'Resource {resource_name} has been deleted.',
  resource_import_succeeded: 'Resource {resource_name} has been imported.',
  resource_restart_failed: 'Resource {resource_name} restart has failed.',
  resource_restart_scheduled: 'Resource {resource_name} has been scheduled to restart.',
  resource_restart_succeeded: 'Resource {resource_name} has been restarted.',
  resource_start_failed: 'Resource {resource_name} start has failed.',
  resource_start_scheduled: 'Resource {resource_name} has been scheduled to start.',
  resource_start_succeeded: 'Resource {resource_name} has been started.',
  resource_stop_failed: 'Resource {resource_name} stop has failed.',
  resource_stop_scheduled: 'Resource {resource_name} has been scheduled to stop.',
  resource_stop_succeeded: 'Resource {resource_name} has been stopped.',
  resource_update_succeeded: 'Resource {resource_name} has been updated.',
  role_granted: 'User {affected_user_full_name} has gained role of {role_name}.',
  role_revoked: 'User {affected_user_full_name} has revoked role of {role_name}.',
  service_project_link_creation_failed: 'Creation of service project link {service_name} has failed',
  ssh_key_creation_succeeded: 'SSH key {ssh_key_name} has been created.',
  ssh_key_deletion_succeeded: 'SSH key {ssh_key_name} has been deleted.',
  user_activated: 'User {affected_user_full_name} has been activated.',
  user_creation_succeeded: 'User {affected_user_full_name} has been created.',
  user_deactivated: 'User {affected_user_full_name} has been deactivated.',
  user_deletion_succeeded: 'User {affected_user_full_name} has been deleted.',
  user_organization_approved: 'User {affected_user_full_name} has been approved for organization {affected_organization}.',
  user_organization_claimed: 'User {affected_user_full_name} has claimed organization {affected_organization}.',
  user_organization_rejected: 'User {affected_user_full_name} claim for organization {affected_organization} has been rejected.',
  user_organization_removed: 'User {affected_user_full_name} has been removed from organization {affected_organization}.',
  user_password_updated: 'Password has been changed for user {affected_user_full_name}.',
  user_update_succeeded: 'User {affected_user_full_name} has been updated.'
};

export const EVENT_ICONS_TYPES = {
  auth: ['Authentication events', 'user'],
  invoice: ['Invoice events', 'customer'],
  user: ['Key management events', 'user'],
  customer: ['Organization events', 'customer'],
  payment: ['Payment events', 'customer'],
  project: ['Project events', 'project'],
  service: ['Providers events', 'service'],
  resource: ['Resource events', 'resource'],
  role: ['Role management events', 'user'],
  quota: ['Quota events', 'customer'],
  ssh: ['SSH key events', 'key'],
};

export const EVENT_ROUTES = {
  affected_user: 'users.details',
  user: 'users.details',
  project: 'project.details',
  customer: 'organization.details',
  affected_organization: 'organization.details',
  instance: 'resources.details',
  resource: 'resources.details',
  service: 'organization.details',
};

export const DELETION_EVENTS = [
  'customer_deletion_succeeded',
  'invoice_deletion_succeeded',
  'project_deletion_succeeded',
  'project_group_deletion_succeeded',
  'resource_deleted',
  'ssh_key_deletion_succeeded',
  'user_deletion_succeeded'
];
