import { Event } from './types';

export const event1: Event = {
  user_uuid: '123',
  user_username: 'someone',
  user_full_name: 'Some One',
  importance: 'normal',
  ['@timestamp']: '2016-01-05',
  ip_address: '192.168.11.101',
  event_type: 'role_granted',
  error_message: 'Extreme mistake',
  project_uuid: '234',
  project_name: 'Waldur Gate',
  link: 'http://domain.com',
  issue_link: 'http://domain.com/123',
  customer_uuid: '345',
  customer_name: 'Oxford University',
  service_uuid: '456',
  service_name: 'Service',
  service_type: 'Specific',
  resource_uuid: '567',
  resource_full_name: 'Particular Resource',
  resource_configuration: 'ResConf',
  resource_type: 'ResType',
  message: 'Oh no, I have to write a message down!',
};
