import { Form, Stack } from 'react-bootstrap';

import { CopyToClipboardButton } from '@/core/CopyToClipboardButton';
import { formatMediumDateTime } from '@/core/dateUtils';
import { SecretField } from '@/form';
import { translate } from '@/i18n';
import { ModalDialog } from '@/modal/ModalDialog';
import { Field } from '@/resource/summary';

interface OwnProps {
  resolve: { username; token; expiresAt };
}

export const ServiceAccountShowInfoDialog = ({ resolve }: OwnProps) => {
  return (
    <ModalDialog title={translate('Your API token')} closeButton>
      <Form.Group className="mb-7">
        <Form.Label>{translate('Username')}</Form.Label>
        <Form.Control value={resolve.username} disabled />
        <Form.Text className="text-muted">
          {translate('Generated by server')}
        </Form.Text>
      </Form.Group>
      <Form.Group className="mb-7">
        <Form.Label>{translate('API token')}</Form.Label>
        <Stack gap={2} direction="horizontal">
          <SecretField
            input={{ value: resolve.token } as any}
            disabled
            className="flex-grow-1"
          />

          <CopyToClipboardButton
            value={resolve.token}
            size={20}
            buttonClassName="btn btn-text-secondary btn-icon"
            onlyButton
          />
        </Stack>
        <Form.Text className="text-muted">
          {translate(
            "This token won't be shown again, but you can regenerate it later.",
          )}
        </Form.Text>
      </Form.Group>
      <Field
        label={translate('Valid till')}
        value={formatMediumDateTime(resolve.expiresAt)}
        labelClass="fw-bolder"
      />
    </ModalDialog>
  );
};
