import resourceUtils from './resource-utils-service';
import resourceDetails from './resource-details';
import resourceRoutes from './routes';
import resourceHeader from './resource-header';
import resourceLinkState from './resource-link-state';
import resourcesService from './resources-service';
import resourceSummaryModule from './summary/module';
import resourceBreadcrumbsModule from './breadcrumbs/module';
import resourceStateModule from './state/module';
import resourceTabsModule from './tabs/module';
import resourcesListModule from './list/module';
import monitoringModule from './monitoring/module';
import actionsModule from './actions/module';
import filtersModule from './filters';

export default module => {
  module.service('resourceUtils', resourceUtils);
  module.component('resourceDetails', resourceDetails);
  module.component('resourceHeader', resourceHeader);
  module.component('resourceLinkState', resourceLinkState);
  module.config(resourceRoutes);
  module.service('resourcesService', resourcesService);
  resourceSummaryModule(module);
  resourceBreadcrumbsModule(module);
  resourceStateModule(module);
  resourceTabsModule(module);
  resourcesListModule(module);
  monitoringModule(module);
  actionsModule(module);
  filtersModule(module);
};
