// WARNING: This file is auto-generated from src/waldur_core/core/management/commands/print_settings_description.py
// Do not edit it manually. All manual changes would be overridden.
import { translate } from '@/i18n';

export const SettingsDescription = [
  {
    description: translate('Branding'),
    items: [
      {
        key: 'SITE_NAME',
        description: translate('Human-friendly name of the Waldur deployment.'),
        default: 'Waldur',
        type: 'string',
      },
      {
        key: 'SHORT_PAGE_TITLE',
        description: translate('It is used as prefix for page title.'),
        default: 'Waldur',
        type: 'string',
      },
      {
        key: 'FULL_PAGE_TITLE',
        description: translate('It is used as default page title if it\'s not specified explicitly.'),
        default: 'Waldur | Cloud Service Management',
        type: 'string',
      },
      {
        key: 'SITE_DESCRIPTION',
        description: translate('Description of the Waldur deployment.'),
        default: 'Your single pane of control for managing projects, teams and resources in a self-service manner.',
        type: 'string',
      },
      {
        key: 'HOMEPORT_URL',
        description: translate('It is used for rendering callback URL in HomePort'),
        default: 'https://example.com/',
        type: 'string',
      },
      {
        key: 'RANCHER_USERNAME_INPUT_LABEL',
        description: translate('Label for the username field in Rancher external user resource access management.'),
        default: 'Username',
        type: 'string',
      },
      {
        key: 'DISCLAIMER_AREA_TEXT',
        description: translate('Text content rendered in the disclaimer area below the footer.'),
        default: '',
        type: 'text_field',
      },
    ],
  },
  {
    description: translate('Marketplace Branding'),
    items: [
      {
        key: 'SITE_ADDRESS',
        description: translate('It is used in marketplace order header.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SITE_EMAIL',
        description: translate('It is used in marketplace order header and UI footer.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SITE_PHONE',
        description: translate('It is used in marketplace order header and UI footer.'),
        default: '',
        type: 'string',
      },
      {
        key: 'CURRENCY_NAME',
        description: translate('It is used in marketplace order details and invoices for currency formatting.'),
        default: 'EUR',
        type: 'string',
      },
      {
        key: 'MARKETPLACE_LANDING_PAGE',
        description: translate('Marketplace landing page title.'),
        default: 'Marketplace',
        type: 'string',
      },
      {
        key: 'MARKETPLACE_LAYOUT_MODE',
        description: translate('Default marketplace layout mode.'),
        default: 'classic',
        type: 'choice_field',
        options: [{ value: 'classic', label: 'Classic' }, { value: 'sidebar', label: 'Sidebar' }, { value: 'carousel', label: 'Carousel' }],
      },
      {
        key: 'MARKETPLACE_CARD_STYLE',
        description: translate('Default marketplace offering card style.'),
        default: 'detailed',
        type: 'choice_field',
        options: [{ value: 'compact', label: 'Compact' }, { value: 'detailed', label: 'Detailed' }, { value: 'list', label: 'List' }, { value: 'minimal', label: 'Minimal' }],
      },
      {
        key: 'COUNTRIES',
        description: translate('It is used in organization creation dialog in order to limit country choices to predefined set.'),
        default: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'EU', 'FI', 'FR', 'GB', 'GE', 'GR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LT', 'LU', 'LV', 'MC', 'MK', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'UA'],
        type: 'country_list_field',
      },
    ],
  },
  {
    description: translate('Marketplace visibility & access'),
    items: [
      {
        key: 'ANONYMOUS_USER_CAN_VIEW_OFFERINGS',
        description: translate('Allow anonymous users to see shared offerings in active, paused and archived states'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'ANONYMOUS_USER_CAN_VIEW_PLANS',
        description: translate('Allow anonymous users to see plans'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'RESTRICTED_OFFERING_VISIBILITY_MODE',
        description: translate('Controls offering visibility for regular users. \'show_all\': Show all shared offerings (current behavior). \'show_restricted_disabled\': Show all but mark inaccessible as disabled. \'hide_inaccessible\': Hide offerings user cannot access. \'require_membership\': Hide all unless user belongs to an organization/project.'),
        default: 'show_all',
        type: 'choice_field',
        options: [{ value: 'show_all', label: 'Show all shared offerings' }, { value: 'show_restricted_disabled', label: 'Show all but mark inaccessible as disabled' }, { value: 'hide_inaccessible', label: 'Hide offerings user cannot access' }, { value: 'require_membership', label: 'Hide all unless user belongs to an organization/project' }],
      },
      {
        key: 'SHOW_OFFERING_COVER_IMAGE',
        description: translate('Show offering cover image as a banner above the name on the offering page.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'ENFORCE_USER_CONSENT_FOR_OFFERINGS',
        description: translate('If True, users must have active consent to access offerings that have active Terms of Service.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'ENFORCE_OFFERING_USER_PROFILE_COMPLETENESS',
        description: translate('If True, service providers only see offering users whose profiles have all exposed attributes filled (per OfferingUserAttributeConfig).'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'ALLOW_SERVICE_PROVIDER_OFFERING_MANAGEMENT',
        description: translate('If true, service provider owners and managers can manage offering lifecycle (activate, pause, unpause, archive, draft, delete) without staff approval.'),
        default: false,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Marketplace notifications'),
    items: [
      {
        key: 'NOTIFY_STAFF_ABOUT_APPROVALS',
        description: translate('If true, users with staff role are notified when request for order approval is generated'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'NOTIFY_ABOUT_RESOURCE_CHANGE',
        description: translate('If true, notify users about resource changes from Marketplace perspective. Can generate duplicate events if plugins also log'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'DISABLE_SENDING_NOTIFICATIONS_ABOUT_RESOURCE_UPDATE',
        description: translate('Disable only resource update events.'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'ENABLE_STALE_RESOURCE_NOTIFICATIONS',
        description: translate('Enable reminders to owners about resources of shared offerings that have not generated any cost for the last 3 months.'),
        default: false,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Offerings & orders'),
    items: [
      {
        key: 'THUMBNAIL_SIZE',
        description: translate('Size of the thumbnail to generate when screenshot is uploaded for an offering.'),
        default: '120x120',
        type: 'string',
      },
      {
        key: 'DISABLED_OFFERING_TYPES',
        description: translate('List of offering types disabled for creation and selection.'),
        default: [],
        type: 'multiple_choice_field',
        options: [{ value: 'Support.OfferingTemplate', label: 'Support' }, { value: 'Marketplace.Booking', label: 'Booking' }, { value: 'Marketplace.Basic', label: 'Basic' }, { value: 'OpenStack.Tenant', label: 'OpenStack Tenant' }, { value: 'OpenStack.Instance', label: 'OpenStack Instance' }, { value: 'OpenStack.Volume', label: 'OpenStack Volume' }, { value: 'Marketplace.Rancher', label: 'Rancher' }, { value: 'VMware.VirtualMachine', label: 'VMware Virtual Machine' }, { value: 'Waldur.RemoteOffering', label: 'Remote Offering' }, { value: 'Marketplace.Script', label: 'Script' }, { value: 'SlurmInvoices.SlurmPackage', label: 'SLURM Package' }, { value: 'Marketplace.Slurm', label: 'Site Agent' }],
      },
      {
        key: 'ENABLE_ORDER_START_DATE',
        description: translate('Allow setting start date to control when resource creation order is processed.'),
        default: false,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Marketplace development'),
    items: [
      {
        key: 'ENABLE_MOCK_SERVICE_ACCOUNT_BACKEND',
        description: translate('Enable mock returns for the service account service'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'ENABLE_MOCK_COURSE_ACCOUNT_BACKEND',
        description: translate('Enable mock returns for the course account service'),
        default: false,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Project'),
    items: [
      {
        key: 'PROJECT_END_DATE_MANDATORY',
        description: translate('If true, project end date field becomes mandatory when creating or updating projects.'),
        default: false,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Telemetry'),
    items: [
      {
        key: 'TELEMETRY_URL',
        description: translate('URL for sending telemetry data.'),
        default: 'https://telemetry.waldur.com/',
        type: 'string',
      },
      {
        key: 'TELEMETRY_VERSION',
        description: translate('Telemetry service version.'),
        default: 1,
        type: 'integer',
      },
    ],
  },
  {
    description: translate('Custom Scripts'),
    items: [
      {
        key: 'SCRIPT_RUN_MODE',
        description: translate('Type of jobs deployment. Valid values: "docker" for simple docker deployment, "k8s" for Kubernetes-based one'),
        default: 'docker',
        type: 'choice_field',
        options: [{ value: 'docker', label: 'Docker' }, { value: 'k8s', label: 'Kubernetes' }],
      },
      {
        key: 'DOCKER_CLIENT',
        description: translate('Options for docker client. See also: <https://docker-py.readthedocs.io/en/stable/client.html#docker.client.DockerClient>'),
        default: {'base_url': 'unix:///var/run/docker.sock'},
        type: 'dict_field',
      },
      {
        key: 'DOCKER_RUN_OPTIONS',
        description: translate('Options for docker runtime. See also: <https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.run>'),
        default: {'mem_limit': '512m'},
        type: 'dict_field',
      },
      {
        key: 'DOCKER_SCRIPT_DIR',
        description: translate('Path to folder on executor machine where to create temporary submission scripts. If None, uses OS-dependent location. OS X users, see <https://github.com/docker/for-mac/issues/1532>'),
        default: '',
        type: 'string',
      },
      {
        key: 'DOCKER_REMOVE_CONTAINER',
        description: translate('Remove Docker container after script execution'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'DOCKER_IMAGES',
        description: translate('Key is command to execute script, value is a dictionary of image name and command.'),
        default: {'python': {'image': 'python:3.12-alpine', 'command': 'python'}, 'shell': {'image': 'alpine:3', 'command': 'sh'}, 'ansible': {'image': 'alpine/ansible:2.18.6', 'command': 'ansible-playbook'}},
        type: 'dict_field',
      },
      {
        key: 'DOCKER_VOLUME_NAME',
        description: translate('A name of the shared volume to store scripts'),
        default: 'waldur-docker-compose_waldur_script_launchzone',
        type: 'string',
      },
      {
        key: 'K8S_NAMESPACE',
        description: translate('Kubernetes namespace where jobs will be executed'),
        default: 'default',
        type: 'string',
      },
      {
        key: 'K8S_CONFIG_PATH',
        description: translate('Path to Kubernetes configuration file'),
        default: '~/.kube/config',
        type: 'string',
      },
      {
        key: 'K8S_JOB_TIMEOUT',
        description: translate('Timeout for execution of one Kubernetes job in seconds'),
        default: 1800,
        type: 'integer',
      },
    ],
  },
  {
    description: translate('Notifications'),
    items: [
      {
        key: 'COMMON_FOOTER_TEXT',
        description: translate('Common footer in txt format for all emails.'),
        default: '',
        type: 'text_field',
      },
      {
        key: 'COMMON_FOOTER_HTML',
        description: translate('Common footer in html format for all emails.'),
        default: '',
        type: 'html_field',
      },
      {
        key: 'MAINTENANCE_ANNOUNCEMENT_NOTIFY_BEFORE_MINUTES',
        description: translate('How many minutes before scheduled maintenance users should be notified.'),
        default: 60,
        type: 'integer',
      },
      {
        key: 'MAINTENANCE_ANNOUNCEMENT_NOTIFY_SYSTEM',
        description: translate('How maintenance notifications are delivered.'),
        default: ['AdminAnnouncement'],
        type: 'multiple_choice_field',
        options: [{ value: 'AdminAnnouncement', label: 'AdminAnnouncement' }, { value: 'BroadcastMessage', label: 'BroadcastMessage' }],
      },
    ],
  },
  {
    description: translate('Links'),
    items: [
      {
        key: 'DOCS_URL',
        description: translate('Renders link to docs in header'),
        default: '',
        type: 'url_field',
      },
      {
        key: 'HERO_LINK_LABEL',
        description: translate('Label for link in hero section of HomePort landing page. It can be lead to support site or blog post.'),
        default: '',
        type: 'string',
      },
      {
        key: 'HERO_LINK_URL',
        description: translate('Link URL in hero section of HomePort landing page.'),
        default: '',
        type: 'url_field',
      },
      {
        key: 'SUPPORT_PORTAL_URL',
        description: translate('Link URL to support portal. Rendered as a shortcut on dashboard'),
        default: '',
        type: 'url_field',
      },
    ],
  },
  {
    description: translate('Theme'),
    items: [
      {
        key: 'SIDEBAR_STYLE',
        description: translate('Style of sidebar.'),
        default: 'dark',
        type: 'choice_field',
        options: [{ value: 'primary', label: 'Primary' }, { value: 'accent', label: 'Dark primary' }, { value: 'accent-light', label: 'Light primary' }, { value: 'dark', label: 'Dark' }, { value: 'light', label: 'Light' }, { value: 'auto', label: 'Match theme' }],
      },
      {
        key: 'FONT_FAMILY',
        description: translate('Font family used in the UI.'),
        default: 'Inter',
        type: 'choice_field',
        options: [{ value: 'Inter', label: 'Inter' }, { value: 'Maven Pro', label: 'Maven Pro' }],
      },
      {
        key: 'BRAND_COLOR',
        description: translate('Brand color is used for button background.'),
        default: '#307300',
        type: 'color_field',
      },
      {
        key: 'DISABLE_DARK_THEME',
        description: translate('Toggler to disable dark theme.'),
        default: false,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Login page'),
    items: [
      {
        key: 'LOGIN_PAGE_LAYOUT',
        description: translate('Login page layout style.'),
        default: 'split-screen',
        type: 'choice_field',
        options: [{ value: 'split-screen', label: 'Split-screen' }, { value: 'centered-card', label: 'Centered-card' }, { value: 'minimal', label: 'Minimal' }, { value: 'full-hero', label: 'Full-hero' }, { value: 'gradient', label: 'Gradient' }, { value: 'stacked', label: 'Stacked' }, { value: 'right-split', label: 'Right-split' }, { value: 'glassmorphism', label: 'Glassmorphism' }, { value: 'neumorphism', label: 'Neumorphism' }, { value: 'animated-gradient', label: 'Animated-gradient' }, { value: 'video-background', label: 'Video-background' }, { value: 'bottom-sheet', label: 'Bottom-sheet' }, { value: 'tabbed', label: 'Tabbed' }, { value: 'wizard', label: 'Wizard' }, { value: 'stats', label: 'Stats' }, { value: 'news', label: 'News' }, { value: 'carousel', label: 'Carousel' }, { value: 'logo-watermark', label: 'Logo-watermark' }, { value: 'brand-pattern', label: 'Brand-pattern' }, { value: 'duotone', label: 'Duotone' }, { value: 'diagonal', label: 'Diagonal' }, { value: 'time-based', label: 'Time-based' }, { value: 'seasonal', label: 'Seasonal' }, { value: 'weather', label: 'Weather' }],
      },
      {
        key: 'LOGIN_PAGE_VIDEO_URL',
        description: translate('Video URL for the video-background login page layout. Supports MP4 format. Leave empty to use default sample video.'),
        default: '',
        type: 'url_field',
      },
      {
        key: 'LOGIN_PAGE_STATS',
        description: translate('Stats displayed in the Stats login page layout. List of objects with \'value\' and \'label\' keys, e.g., [{\'value\': \'10K+\', \'label\': \'Active Users\'}, {\'value\': \'99.9%\', \'label\': \'Uptime\'}].'),
        default: [],
        type: 'json_list_field',
      },
      {
        key: 'LOGIN_PAGE_CAROUSEL_SLIDES',
        description: translate('Carousel slides displayed in the Carousel login page layout. List of objects with \'title\' and \'subtitle\' keys, e.g., [{\'title\': \'Welcome\', \'subtitle\': \'Get started with our platform\'}].'),
        default: [],
        type: 'json_list_field',
      },
      {
        key: 'LOGIN_PAGE_NEWS',
        description: translate('News items displayed in the News login page layout. List of objects with \'date\', \'title\', \'description\', and \'tag\' keys. Supported tags: Feature, Update, Security, Announcement, Maintenance. Example: [{\'date\': \'Jan 2025\', \'title\': \'New Feature\', \'description\': \'Description here\', \'tag\': \'Feature\'}].'),
        default: [],
        type: 'json_list_field',
      },
    ],
  },
  {
    description: translate('Images'),
    items: [
      {
        key: 'SIDEBAR_LOGO',
        description: translate('The image rendered at the top of sidebar menu in HomePort.'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'SIDEBAR_LOGO_MOBILE',
        description: translate('The image rendered at the top of mobile sidebar menu in HomePort.'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'SIDEBAR_LOGO_DARK',
        description: translate('The image rendered at the top of sidebar menu in dark mode.'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'POWERED_BY_LOGO',
        description: translate('The image rendered at the bottom of login menu in HomePort.'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'HERO_IMAGE',
        description: translate('The image rendered at hero section of HomePort landing page.'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'MARKETPLACE_HERO_IMAGE',
        description: translate('The image rendered at hero section of Marketplace landing page. Please, use a wide image (min. 1920×600px) with no text or logos. Keep the center area clean, and choose a darker image for dark mode or a brighter image for light mode.'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'CALL_MANAGEMENT_HERO_IMAGE',
        description: translate('The image rendered at hero section of Call Management landing page. Please, use a wide image (min. 1920×600px) with no text or logos. Keep the center area clean, and choose a darker image for dark mode or a brighter image for light mode.'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'LOGIN_LOGO',
        description: translate('A custom .png image file for login page'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'LOGIN_LOGO_MULTILINGUAL',
        description: translate('Language-specific login logos. Dict mapping language codes to image paths, e.g., {\'de\': \'path/to/german_logo.png\'}. Falls back to LOGIN_LOGO if requested language not found.'),
        default: {},
        type: 'multilingual_image_field',
      },
      {
        key: 'FAVICON',
        description: translate('A custom favicon .png image file'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'OFFERING_LOGO_PLACEHOLDER',
        description: translate('Default logo for offering'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'KEYCLOAK_ICON',
        description: translate('A custom PNG icon for Keycloak login button'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'DISCLAIMER_AREA_LOGO',
        description: translate('The logo image rendered in the disclaimer area below the footer.'),
        default: '',
        type: 'image_field',
      },
    ],
  },
  {
    description: translate('Service desk integration settings'),
    items: [
      {
        key: 'WALDUR_SUPPORT_ENABLED',
        description: translate('Toggler for support plugin.'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'WALDUR_SUPPORT_ACTIVE_BACKEND_TYPE',
        description: translate('Type of support backend.'),
        default: 'atlassian',
        type: 'choice_field',
        options: [{ value: 'atlassian', label: 'Atlassian' }, { value: 'zammad', label: 'Zammad' }, { value: 'smax', label: 'SMAX' }],
      },
      {
        key: 'WALDUR_SUPPORT_DISPLAY_REQUEST_TYPE',
        description: translate('Toggler for request type displaying'),
        default: true,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Atlassian settings'),
    items: [
      {
        key: 'ATLASSIAN_API_URL',
        description: translate('Atlassian API server URL'),
        default: 'https://example.com/',
        type: 'url_field',
      },
      {
        key: 'ATLASSIAN_USERNAME',
        description: translate('Username for access user'),
        default: 'USERNAME',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_PASSWORD',
        description: translate('Password for access user'),
        default: 'PASSWORD',
        type: 'secret_field',
      },
      {
        key: 'ATLASSIAN_EMAIL',
        description: translate('Email for access user'),
        default: '',
        type: 'email_field',
      },
      {
        key: 'ATLASSIAN_TOKEN',
        description: translate('Token for access user'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'ATLASSIAN_PERSONAL_ACCESS_TOKEN',
        description: translate('Personal Access Token for user'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'ATLASSIAN_OAUTH2_CLIENT_ID',
        description: translate('OAuth 2.0 Client ID'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'ATLASSIAN_OAUTH2_ACCESS_TOKEN',
        description: translate('OAuth 2.0 Access Token'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'ATLASSIAN_OAUTH2_TOKEN_TYPE',
        description: translate('OAuth 2.0 Token Type'),
        default: 'Bearer',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_PROJECT_ID',
        description: translate('Service desk ID or key'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_DEFAULT_OFFERING_ISSUE_TYPE',
        description: translate('Issue type used for request-based item processing.'),
        default: 'Service Request',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_EXCLUDED_ATTACHMENT_TYPES',
        description: translate('Comma-separated list of file extenstions not allowed for attachment.'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_AFFECTED_RESOURCE_FIELD',
        description: translate('Affected resource field name'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_DESCRIPTION_TEMPLATE',
        description: translate('Template for issue description'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_SUMMARY_TEMPLATE',
        description: translate('Template for issue summary'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_IMPACT_FIELD',
        description: translate('Impact field name'),
        default: 'Impact',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_ORGANISATION_FIELD',
        description: translate('Organisation field name'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_RESOLUTION_SLA_FIELD',
        description: translate('Resolution SLA field name'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_PROJECT_FIELD',
        description: translate('Project field name'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_REPORTER_FIELD',
        description: translate('Reporter field name'),
        default: 'Original Reporter',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_CALLER_FIELD',
        description: translate('Caller field name'),
        default: 'Caller',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_SLA_FIELD',
        description: translate('SLA field name'),
        default: 'Time to first response',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_LINKED_ISSUE_TYPE',
        description: translate('Type of linked issue field name'),
        default: 'Relates',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_SATISFACTION_FIELD',
        description: translate('Customer satisfaction field name'),
        default: 'Customer satisfaction',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_REQUEST_FEEDBACK_FIELD',
        description: translate('Request feedback field name'),
        default: 'Request feedback',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_TEMPLATE_FIELD',
        description: translate('Template field name'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_WALDUR_BACKEND_ID_FIELD',
        description: translate('Waldur backend ID custom field ID (fallback when field lookup by name fails)'),
        default: 'customfield_10200',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_CUSTOM_ISSUE_FIELD_MAPPING_ENABLED',
        description: translate('Should extra issue field mappings be applied'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'ATLASSIAN_SHARED_USERNAME',
        description: translate('Is Service Desk username the same as in Waldur'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'ATLASSIAN_VERIFY_SSL',
        description: translate('Toggler for SSL verification'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'ATLASSIAN_USE_OLD_API',
        description: translate('Toggler for legacy API usage.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'ATLASSIAN_MAP_WALDUR_USERS_TO_SERVICEDESK_AGENTS',
        description: translate('Toggler for mapping between waldur user and service desk agents.'),
        default: false,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Zammad settings'),
    items: [
      {
        key: 'ZAMMAD_API_URL',
        description: translate('Zammad API server URL. For example <https://localhost:8080/>'),
        default: '',
        type: 'url_field',
      },
      {
        key: 'ZAMMAD_TOKEN',
        description: translate('Authorization token.'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'ZAMMAD_GROUP',
        description: translate('The name of the group to which the ticket will be added. If not specified, the first group will be used.'),
        default: '',
        type: 'string',
      },
      {
        key: 'ZAMMAD_ARTICLE_TYPE',
        description: translate('Type of a comment.'),
        default: 'email',
        type: 'choice_field',
        options: [{ value: 'email', label: 'email' }, { value: 'phone', label: 'phone' }, { value: 'web', label: 'web' }, { value: 'note', label: 'note' }, { value: 'sms', label: 'sms' }, { value: 'chat', label: 'chat' }, { value: 'fax', label: 'fax' }, { value: 'twitter status', label: 'twitter status' }, { value: 'twitter direct-message', label: 'twitter direct-message' }, { value: 'facebook feed post', label: 'facebook feed post' }, { value: 'facebook feed comment', label: 'facebook feed comment' }, { value: 'telegram personal-message', label: 'telegram personal-message' }],
      },
      {
        key: 'ZAMMAD_COMMENT_MARKER',
        description: translate('Marker for comment. Used for separating comments made via Waldur from natively added comments.'),
        default: 'Created by Waldur',
        type: 'string',
      },
      {
        key: 'ZAMMAD_COMMENT_PREFIX',
        description: translate('Comment prefix with user info.'),
        default: 'User: {name}',
        type: 'string',
      },
      {
        key: 'ZAMMAD_COMMENT_COOLDOWN_DURATION',
        description: translate('Time in minutes. Time in minutes while comment deletion is available <https://github.com/zammad/zammad/issues/2687/>, <https://github.com/zammad/zammad/issues/3086/>'),
        default: 5,
        type: 'integer',
      },
    ],
  },
  {
    description: translate('SMAX settings'),
    items: [
      {
        key: 'SMAX_API_URL',
        description: translate('SMAX API server URL. For example <https://localhost:8080/>'),
        default: '',
        type: 'url_field',
      },
      {
        key: 'SMAX_TENANT_ID',
        description: translate('User tenant ID.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SMAX_LOGIN',
        description: translate('Authorization login.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SMAX_PASSWORD',
        description: translate('Authorization password.'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'SMAX_ORGANISATION_FIELD',
        description: translate('Organisation field name.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SMAX_PROJECT_FIELD',
        description: translate('Project field name.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SMAX_AFFECTED_RESOURCE_FIELD',
        description: translate('Resource field name.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SMAX_REQUESTS_OFFERING',
        description: translate('Requests offering code for all issues.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SMAX_SECONDS_TO_WAIT',
        description: translate('Duration in seconds of delay between pull user attempts.'),
        default: 1,
        type: 'integer',
      },
      {
        key: 'SMAX_TIMES_TO_PULL',
        description: translate('The maximum number of attempts to pull user from backend.'),
        default: 10,
        type: 'integer',
      },
      {
        key: 'SMAX_CREATION_SOURCE_NAME',
        description: translate('Creation source name.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SMAX_VERIFY_SSL',
        description: translate('Toggler for SSL verification'),
        default: true,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Proposal settings'),
    items: [
      {
        key: 'PROPOSAL_REVIEW_DURATION',
        description: translate('Review duration in days.'),
        default: 7,
        type: 'integer',
      },
      {
        key: 'REVIEWER_PROFILES_ENABLED',
        description: translate('Enable reviewer profile management features.'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'COI_DETECTION_ENABLED',
        description: translate('Enable conflict of interest detection features.'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'COI_DISCLOSURE_REQUIRED',
        description: translate('Require reviewers to submit COI disclosure before reviewing proposals.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'AUTOMATED_MATCHING_ENABLED',
        description: translate('Enable automated reviewer-proposal matching algorithms.'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'COI_COAUTHORSHIP_LOOKBACK_YEARS',
        description: translate('Default number of years to look back for co-authorship COI detection.'),
        default: 5,
        type: 'integer',
      },
      {
        key: 'COI_COAUTHORSHIP_THRESHOLD_PAPERS',
        description: translate('Default number of co-authored papers to trigger a COI.'),
        default: 2,
        type: 'integer',
      },
      {
        key: 'COI_INSTITUTIONAL_LOOKBACK_YEARS',
        description: translate('Default number of years after leaving institution before COI expires.'),
        default: 3,
        type: 'integer',
      },
    ],
  },
  {
    description: translate('ORCID integration settings'),
    items: [
      {
        key: 'ORCID_CLIENT_ID',
        description: translate('ORCID OAuth2 Client ID for reviewer profile integration.'),
        default: '',
        type: 'string',
      },
      {
        key: 'ORCID_CLIENT_SECRET',
        description: translate('ORCID OAuth2 Client Secret.'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'ORCID_REDIRECT_URI',
        description: translate('ORCID OAuth2 Redirect URI. Typically {HOMEPORT_URL}/orcid-callback/'),
        default: '',
        type: 'url_field',
      },
      {
        key: 'ORCID_API_URL',
        description: translate('ORCID API Base URL. Use https://pub.sandbox.orcid.org/v3.0 for testing.'),
        default: 'https://pub.orcid.org/v3.0',
        type: 'url_field',
      },
      {
        key: 'ORCID_AUTH_URL',
        description: translate('ORCID OAuth Authorization URL. Use https://sandbox.orcid.org/oauth for testing.'),
        default: 'https://orcid.org/oauth',
        type: 'url_field',
      },
      {
        key: 'ORCID_SANDBOX_MODE',
        description: translate('Use ORCID sandbox environment for testing. When enabled, uses sandbox URLs automatically.'),
        default: false,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Publication API settings'),
    items: [
      {
        key: 'SEMANTIC_SCHOLAR_API_KEY',
        description: translate('Semantic Scholar API Key for publication imports. Optional but recommended for higher rate limits.'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'CROSSREF_MAILTO',
        description: translate('Email address for CrossRef API polite pool. Provides higher rate limits.'),
        default: '',
        type: 'email_field',
      },
    ],
  },
  {
    description: translate('Table settings'),
    items: [
      {
        key: 'USER_TABLE_COLUMNS',
        description: translate('Comma-separated list of columns for users table.'),
        default: '',
        type: 'string',
      },
    ],
  },
  {
    description: translate('Localization'),
    items: [
      {
        key: 'LANGUAGE_CHOICES',
        description: translate('List of enabled languages'),
        default: 'en,et,lt,lv,ru,it,de,da,sv,es,fr,nb,ar,cs',
        type: 'string',
      },
    ],
  },
  {
    description: translate('Authentication settings'),
    items: [
      {
        key: 'AUTO_APPROVE_USER_TOS',
        description: translate('Mark terms of services as approved for new users.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'DEFAULT_IDP',
        description: translate('Triggers authentication flow at once.'),
        default: '',
        type: 'choice_field',
        options: [{ value: '', label: 'Not configured' }, { value: 'tara', label: 'TARA' }, { value: 'eduteams', label: 'eduTEAMS' }, { value: 'keycloak', label: 'Keycloak' }],
      },
      {
        key: 'DEACTIVATE_USER_IF_NO_ROLES',
        description: translate('Deactivate user if all roles are revoked (except staff/support)'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'OIDC_BLOCK_CREATION_OF_UNINVITED_USERS',
        description: translate('If true, block creation of an account on OIDC login if user email is not provided or provided and is not in the list of one of the active invitations or matching active group invitation email patterns.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'OIDC_BLOCK_CREATION_OF_UNINVITED_USERS_RESPONSE_MESSAGE',
        description: translate('The message to show when OIDC account creation is blocked for uninvited users.'),
        default: 'Account creation is blocked for uninvited users.',
        type: 'text_field',
      },
      {
        key: 'OIDC_MATCHMAKING_BY_EMAIL',
        description: translate('If true, when OIDC login fails to find a user by the primary lookup field, attempt a secondary lookup by email before creating a new user. On successful email match, the user\'s primary lookup field is updated to the OIDC claim value.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'OIDC_ACCESS_TOKEN_ENABLED',
        description: translate('If true, OIDC complete view returns access token instead of Waldur token'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'REMOTE_EDUTEAMS_REFRESH_TOKEN',
        description: translate('Rotating OAuth2 refresh token for remote eduTEAMS API access. Automatically updated by the periodic token rotation task. If empty, falls back to REMOTE_EDUTEAMS_REFRESH_TOKEN from Django settings.'),
        default: '',
        type: 'secret_field',
      },
    ],
  },
  {
    description: translate('Invitation settings'),
    items: [
      {
        key: 'ENABLE_STRICT_CHECK_ACCEPTING_INVITATION',
        description: translate('If true, user email in Waldur database and in invitatation must strictly match.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'INVITATION_DISABLE_MULTIPLE_ROLES',
        description: translate('Do not allow user to accept multiple roles within the same scope (project or organization) using invitation. When enabled, users can still accept invitations to different scopes but cannot have multiple roles in the same scope.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'INVITATION_ALLOWED_FIELDS',
        description: translate('Fields that can be provided in invitations for email personalization. These are NOT copied to user profile.'),
        default: ['full_name', 'organization', 'job_title'],
        type: 'multiple_choice_field',
        options: [{ value: 'username', label: 'Username' }, { value: 'registration_method', label: 'Registration method' }, { value: 'first_name', label: 'First name' }, { value: 'last_name', label: 'Last name' }, { value: 'full_name', label: 'Full name' }, { value: 'email', label: 'Email' }, { value: 'phone_number', label: 'Phone number' }, { value: 'organization', label: 'Organization' }, { value: 'job_title', label: 'Job title' }, { value: 'affiliations', label: 'Affiliations' }, { value: 'gender', label: 'Gender' }, { value: 'personal_title', label: 'Personal title' }, { value: 'birth_date', label: 'Birth date' }, { value: 'place_of_birth', label: 'Place of birth' }, { value: 'country_of_residence', label: 'Country of residence' }, { value: 'nationality', label: 'Nationality' }, { value: 'nationalities', label: 'Nationalities' }, { value: 'organization_country', label: 'Organization country' }, { value: 'organization_type', label: 'Organization type' }, { value: 'organization_registry_code', label: 'Organization registry code' }, { value: 'eduperson_assurance', label: 'Eduperson assurance' }, { value: 'civil_number', label: 'Civil number' }, { value: 'identity_source', label: 'Identity source' }],
      },
    ],
  },
  {
    description: translate('User profile settings'),
    items: [
      {
        key: 'DEFAULT_OFFERING_USER_ATTRIBUTES',
        description: translate('Default user attributes exposed to service providers (OfferingUser API) when no explicit config exists.'),
        default: ['username', 'full_name', 'email'],
        type: 'multiple_choice_field',
        options: [{ value: 'username', label: 'Username' }, { value: 'registration_method', label: 'Registration method' }, { value: 'first_name', label: 'First name' }, { value: 'last_name', label: 'Last name' }, { value: 'full_name', label: 'Full name' }, { value: 'email', label: 'Email' }, { value: 'phone_number', label: 'Phone number' }, { value: 'organization', label: 'Organization' }, { value: 'job_title', label: 'Job title' }, { value: 'affiliations', label: 'Affiliations' }, { value: 'gender', label: 'Gender' }, { value: 'personal_title', label: 'Personal title' }, { value: 'birth_date', label: 'Birth date' }, { value: 'place_of_birth', label: 'Place of birth' }, { value: 'country_of_residence', label: 'Country of residence' }, { value: 'nationality', label: 'Nationality' }, { value: 'nationalities', label: 'Nationalities' }, { value: 'organization_country', label: 'Organization country' }, { value: 'organization_type', label: 'Organization type' }, { value: 'organization_registry_code', label: 'Organization registry code' }, { value: 'eduperson_assurance', label: 'Eduperson assurance' }, { value: 'civil_number', label: 'Civil number' }, { value: 'identity_source', label: 'Identity source' }],
      },
      {
        key: 'DEFAULT_CALL_USER_ATTRIBUTES',
        description: translate('Default applicant attributes exposed to call reviewers when no explicit CallApplicantVisibilityConfig exists.'),
        default: ['username', 'full_name', 'email'],
        type: 'multiple_choice_field',
        options: [{ value: 'username', label: 'Username' }, { value: 'registration_method', label: 'Registration method' }, { value: 'first_name', label: 'First name' }, { value: 'last_name', label: 'Last name' }, { value: 'full_name', label: 'Full name' }, { value: 'email', label: 'Email' }, { value: 'phone_number', label: 'Phone number' }, { value: 'organization', label: 'Organization' }, { value: 'job_title', label: 'Job title' }, { value: 'affiliations', label: 'Affiliations' }, { value: 'gender', label: 'Gender' }, { value: 'personal_title', label: 'Personal title' }, { value: 'birth_date', label: 'Birth date' }, { value: 'place_of_birth', label: 'Place of birth' }, { value: 'country_of_residence', label: 'Country of residence' }, { value: 'nationality', label: 'Nationality' }, { value: 'nationalities', label: 'Nationalities' }, { value: 'organization_country', label: 'Organization country' }, { value: 'organization_type', label: 'Organization type' }, { value: 'organization_registry_code', label: 'Organization registry code' }, { value: 'eduperson_assurance', label: 'Eduperson assurance' }, { value: 'civil_number', label: 'Civil number' }, { value: 'identity_source', label: 'Identity source' }],
      },
      {
        key: 'ENABLED_USER_PROFILE_ATTRIBUTES',
        description: translate('List of enabled user profile attributes. Controls IdP sync and UI display.'),
        default: ['phone_number', 'organization', 'job_title', 'affiliations'],
        type: 'multiple_choice_field',
        options: [{ value: 'username', label: 'Username' }, { value: 'registration_method', label: 'Registration method' }, { value: 'first_name', label: 'First name' }, { value: 'last_name', label: 'Last name' }, { value: 'full_name', label: 'Full name' }, { value: 'email', label: 'Email' }, { value: 'phone_number', label: 'Phone number' }, { value: 'organization', label: 'Organization' }, { value: 'job_title', label: 'Job title' }, { value: 'affiliations', label: 'Affiliations' }, { value: 'gender', label: 'Gender' }, { value: 'personal_title', label: 'Personal title' }, { value: 'birth_date', label: 'Birth date' }, { value: 'place_of_birth', label: 'Place of birth' }, { value: 'country_of_residence', label: 'Country of residence' }, { value: 'nationality', label: 'Nationality' }, { value: 'nationalities', label: 'Nationalities' }, { value: 'organization_country', label: 'Organization country' }, { value: 'organization_type', label: 'Organization type' }, { value: 'organization_registry_code', label: 'Organization registry code' }, { value: 'eduperson_assurance', label: 'Eduperson assurance' }, { value: 'civil_number', label: 'Civil number' }, { value: 'identity_source', label: 'Identity source' }],
      },
      {
        key: 'MANDATORY_USER_ATTRIBUTES',
        description: translate('List of user profile attributes that are mandatory.'),
        default: [],
        type: 'multiple_choice_field',
        options: [{ value: 'username', label: 'Username' }, { value: 'registration_method', label: 'Registration method' }, { value: 'first_name', label: 'First name' }, { value: 'last_name', label: 'Last name' }, { value: 'full_name', label: 'Full name' }, { value: 'email', label: 'Email' }, { value: 'phone_number', label: 'Phone number' }, { value: 'organization', label: 'Organization' }, { value: 'job_title', label: 'Job title' }, { value: 'affiliations', label: 'Affiliations' }, { value: 'gender', label: 'Gender' }, { value: 'personal_title', label: 'Personal title' }, { value: 'birth_date', label: 'Birth date' }, { value: 'place_of_birth', label: 'Place of birth' }, { value: 'country_of_residence', label: 'Country of residence' }, { value: 'nationality', label: 'Nationality' }, { value: 'nationalities', label: 'Nationalities' }, { value: 'organization_country', label: 'Organization country' }, { value: 'organization_type', label: 'Organization type' }, { value: 'organization_registry_code', label: 'Organization registry code' }, { value: 'eduperson_assurance', label: 'Eduperson assurance' }, { value: 'civil_number', label: 'Civil number' }, { value: 'identity_source', label: 'Identity source' }],
      },
      {
        key: 'ENFORCE_MANDATORY_USER_ATTRIBUTES',
        description: translate('If True, users with incomplete mandatory attributes will be blocked from most API endpoints until they complete their profile.'),
        default: false,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Data privacy settings'),
    items: [
      {
        key: 'USER_DATA_ACCESS_LOGGING_ENABLED',
        description: translate('Enable logging of user profile data access events for GDPR compliance.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'USER_DATA_ACCESS_LOG_RETENTION_DAYS',
        description: translate('Number of days to retain user data access logs before automatic cleanup.'),
        default: 90,
        type: 'integer',
      },
      {
        key: 'USER_DATA_ACCESS_LOG_SELF_ACCESS',
        description: translate('Log when users access their own profile data. Disabled by default to reduce log volume.'),
        default: false,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('FreeIPA settings'),
    items: [
      {
        key: 'FREEIPA_ENABLED',
        description: translate('Enable integration of identity provisioning in configured FreeIPA.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'FREEIPA_HOSTNAME',
        description: translate('Hostname of FreeIPA server.'),
        default: 'ipa.example.com',
        type: 'string',
      },
      {
        key: 'FREEIPA_USERNAME',
        description: translate('Username of FreeIPA user with administrative privileges.'),
        default: 'admin',
        type: 'string',
      },
      {
        key: 'FREEIPA_PASSWORD',
        description: translate('Password of FreeIPA user with administrative privileges'),
        default: 'secret',
        type: 'secret_field',
      },
      {
        key: 'FREEIPA_VERIFY_SSL',
        description: translate('Validate TLS certificate of FreeIPA web interface / REST API'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'FREEIPA_USERNAME_PREFIX',
        description: translate('Prefix to be appended to all usernames created in FreeIPA by Waldur'),
        default: 'waldur_',
        type: 'string',
      },
      {
        key: 'FREEIPA_GROUPNAME_PREFIX',
        description: translate('Prefix to be appended to all group names created in FreeIPA by Waldur'),
        default: 'waldur_',
        type: 'string',
      },
      {
        key: 'FREEIPA_BLACKLISTED_USERNAMES',
        description: translate('List of username that users are not allowed to select'),
        default: ['root'],
        type: 'list_field',
      },
      {
        key: 'FREEIPA_GROUP_SYNCHRONIZATION_ENABLED',
        description: translate('Optionally disable creation of user groups in FreeIPA matching Waldur structure'),
        default: true,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('SCIM settings'),
    items: [
      {
        key: 'SCIM_MEMBERSHIP_SYNC_ENABLED',
        description: translate('Enable SCIM entitlement synchronization to external identity provider.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'SCIM_API_URL',
        description: translate('Base URL of the SCIM API service.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SCIM_API_KEY',
        description: translate('SCIM API key for X-API-Key header.'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'SCIM_URN_NAMESPACE',
        description: translate('URN namespace for SCIM entitlements.'),
        default: '',
        type: 'string',
      },
    ],
  },
  {
    description: translate('API token authentication'),
    items: [
      {
        key: 'OIDC_AUTH_URL',
        description: translate('OIDC authorization endpoint URL. Reserved for future OAuth 2.0 authorization code flow integration.'),
        default: '',
        type: 'string',
      },
      {
        key: 'OIDC_INTROSPECTION_URL',
        description: translate('RFC 7662 Token Introspection endpoint URL. Used to validate API bearer tokens. When a client sends Authorization: Bearer <token>, Waldur calls this endpoint to verify the token is active.'),
        default: '',
        type: 'string',
      },
      {
        key: 'OIDC_CLIENT_ID',
        description: translate('Client ID for HTTP Basic authentication when calling the token introspection endpoint. Required together with OIDC_CLIENT_SECRET and OIDC_INTROSPECTION_URL.'),
        default: '',
        type: 'string',
      },
      {
        key: 'OIDC_CLIENT_SECRET',
        description: translate('Client secret for HTTP Basic authentication when calling the token introspection endpoint. Required together with OIDC_CLIENT_ID and OIDC_INTROSPECTION_URL.'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'OIDC_USER_FIELD',
        description: translate('Field name from the introspection response JSON used to identify the Waldur user. Common values: \'username\', \'email\', \'sub\', \'client_id\'. The value is matched against User.username.'),
        default: 'username',
        type: 'string',
      },
      {
        key: 'OIDC_CACHE_TIMEOUT',
        description: translate('Seconds to cache successful token introspection results. Reduces load on the introspection endpoint. Set to 0 to disable caching. Default: 300 (5 minutes).'),
        default: 300,
        type: 'integer',
      },
      {
        key: 'OIDC_DEFAULT_LOGOUT_URL',
        description: translate('Default logout URL used as fallback when IdentityProvider does not have a logout_url set. This allows configuring a global logout endpoint for OIDC providers that don\'t expose end_session_endpoint in their discovery document.'),
        default: '',
        type: 'url_field',
      },
      {
        key: 'WALDUR_AUTH_SOCIAL_ROLE_CLAIM',
        description: translate('OAuth/OIDC token claim name containing user roles for automatic staff/support assignment. If the claim contains \'staff\', user gets is_staff=True. If it contains \'support\', user gets is_support=True. Leave empty to disable role synchronization from identity provider.'),
        default: '',
        type: 'string',
      },
    ],
  },
  {
    description: translate('Onboarding settings'),
    items: [
      {
        key: 'ONBOARDING_VALIDATION_METHODS',
        description: translate('List of automatic validation methods available for this portal.'),
        default: [],
        type: 'multiple_choice_field',
        options: [{ value: 'ariregister', label: 'ariregister' }, { value: 'wirtschaftscompass', label: 'wirtschaftscompass' }, { value: 'bolagsverket', label: 'bolagsverket' }],
      },
      {
        key: 'ONBOARDING_VERIFICATION_EXPIRY_HOURS',
        description: translate('Number of hours after which onboarding verifications expire.'),
        default: 48,
        type: 'integer',
      },
      {
        key: 'ONBOARDING_ARIREGISTER_BASE_URL',
        description: translate('Base URL for Estonian Äriregister API endpoint.'),
        default: 'https://demo-ariregxmlv6.rik.ee/',
        type: 'url_field',
      },
      {
        key: 'ONBOARDING_ARIREGISTER_USERNAME',
        description: translate('Username for Estonian Äriregister API authentication.'),
        default: '',
        type: 'string',
      },
      {
        key: 'ONBOARDING_ARIREGISTER_PASSWORD',
        description: translate('Password for Estonian Äriregister API authentication.'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'ONBOARDING_ARIREGISTER_TIMEOUT',
        description: translate('Timeout in seconds for Estonian Äriregister API requests.'),
        default: 30,
        type: 'integer',
      },
      {
        key: 'ONBOARDING_WICO_API_URL',
        description: translate('WirtschaftsCompass API server URL'),
        default: 'https://api.wirtschaftscompass.at/',
        type: 'url_field',
      },
      {
        key: 'ONBOARDING_WICO_TOKEN',
        description: translate('WirtschaftsCompass API token'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'ONBOARDING_BOLAGSVERKET_API_URL',
        description: translate('Sweden Business Register API server URL'),
        default: 'https://gw-accept2.api.bolagsverket.se/',
        type: 'url_field',
      },
      {
        key: 'ONBOARDING_BOLAGSVERKET_TOKEN_API_URL',
        description: translate('Bolagsverket OAuth2 token server base URL'),
        default: 'https://portal-accept2.api.bolagsverket.se/',
        type: 'url_field',
      },
      {
        key: 'ONBOARDING_BOLAGSVERKET_CLIENT_ID',
        description: translate('Sweden Business Register API client identifier'),
        default: '',
        type: 'string',
      },
      {
        key: 'ONBOARDING_BOLAGSVERKET_CLIENT_SECRET',
        description: translate('Sweden Business Register API client secret'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'ONBOARDING_BREG_API_URL',
        description: translate('Norway Business Register API server URL'),
        default: 'https://data.brreg.no/',
        type: 'url_field',
      },
    ],
  },
  {
    description: translate('AI assistant settings'),
    items: [
      {
        key: 'AI_ASSISTANT_NAME',
        description: translate('Display name for the AI Assistant persona (e.g. \'Mari\', \'Waldur Assistant\').'),
        default: 'Waldur Assistant',
        type: 'string',
      },
      {
        key: 'AI_ASSISTANT_ENABLED',
        description: translate('Enable AI Assistant feature and calls to the inference service.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'AI_ASSISTANT_ENABLED_ROLES',
        description: translate('Controls which user roles can access the AI Assistant. \'disabled\': No role-based access. \'staff\': Staff users only. \'staff_and_support\': Staff and support users. \'all\': All authenticated users.'),
        default: 'disabled',
        type: 'choice_field',
        options: [{ value: 'disabled', label: 'Disabled' }, { value: 'staff', label: 'Staff users' }, { value: 'staff_and_support', label: 'Staff and support users' }, { value: 'all', label: 'All users' }],
      },
      {
        key: 'AI_ASSISTANT_BACKEND_TYPE',
        description: translate('Type of AI Assistant backend. For example: vllm, openai, ollama.'),
        default: 'vllm',
        type: 'string',
      },
      {
        key: 'AI_ASSISTANT_API_URL',
        description: translate('Base URL for AI Assistant service API.'),
        default: '',
        type: 'url_field',
      },
      {
        key: 'AI_ASSISTANT_API_TOKEN',
        description: translate('API key for authenticating with the AI Assistant service.'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'AI_ASSISTANT_MODEL',
        description: translate('Name of the AI Assistant model to use for inference.'),
        default: 'qwen3.5-122b-nothinking',
        type: 'string',
      },
      {
        key: 'AI_ASSISTANT_SYSTEM_PROMPT_CUSTOM_INSTRUCTIONS',
        description: translate('Additional instructions injected into the AI Assistant system prompt. Use this for organisation-specific context, terminology, FAQ content, or behavioural guidelines. Supports {assistant_name} and {organization} placeholders. Overridden by the active SystemPrompt record when set.'),
        default: '',
        type: 'text_field',
      },
      {
        key: 'AI_ASSISTANT_COMPLETION_KWARGS',
        description: translate('Override keyword arguments merged on top of provider defaults for AI Assistant chat completion. Supported keys: temperature, top_p, top_k, max_tokens, max_completion_tokens, presence_penalty, frequency_penalty, repetition_penalty, stop, seed, reasoning_effort, extra_body. Leave empty to use provider defaults.'),
        default: {},
        type: 'dict_field',
      },
      {
        key: 'AI_ASSISTANT_TOKEN_LIMIT_DAILY',
        description: translate('Default daily token limit (integer). -1 means unlimited.'),
        default: -1,
        type: 'integer',
      },
      {
        key: 'AI_ASSISTANT_TOKEN_LIMIT_WEEKLY',
        description: translate('Default weekly token limit (integer). -1 means unlimited.'),
        default: -1,
        type: 'integer',
      },
      {
        key: 'AI_ASSISTANT_TOKEN_LIMIT_MONTHLY',
        description: translate('Default monthly token limit (integer). -1 means unlimited.'),
        default: -1,
        type: 'integer',
      },
      {
        key: 'AI_ASSISTANT_SESSION_RETENTION_DAYS',
        description: translate('Number of days to retain AI Assistant sessions before automatic deletion. Set to -1 to disable automatic cleanup.'),
        default: 90,
        type: 'integer',
      },
      {
        key: 'AI_ASSISTANT_HISTORY_LIMIT',
        description: translate('Maximum number of past messages included in the AI Assistant context window.'),
        default: 50,
        type: 'integer',
      },
      {
        key: 'AI_ASSISTANT_INJECTION_ALLOWLIST',
        description: translate('Comma-separated allowlist phrases that bypass injection detection.'),
        default: '',
        type: 'string',
      },
    ],
  },
  {
    description: translate('Software catalog general'),
    items: [
      {
        key: 'SOFTWARE_CATALOG_UPDATE_EXISTING_PACKAGES',
        description: translate('Update existing packages during catalog refresh'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'SOFTWARE_CATALOG_CLEANUP_ENABLED',
        description: translate('Enable automatic cleanup of old catalog data'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'SOFTWARE_CATALOG_RETENTION_DAYS',
        description: translate('Number of days to retain old catalog versions'),
        default: 90,
        type: 'integer',
      },
    ],
  },
  {
    description: translate('Software catalog EESSI'),
    items: [
      {
        key: 'SOFTWARE_CATALOG_EESSI_UPDATE_ENABLED',
        description: translate('Enable automated daily updates for EESSI software catalog'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'SOFTWARE_CATALOG_EESSI_VERSION',
        description: translate('EESSI catalog version to load (auto-detect if empty)'),
        default: '',
        type: 'string',
      },
      {
        key: 'SOFTWARE_CATALOG_EESSI_API_URL',
        description: translate('Base URL for EESSI API data'),
        default: 'https://www.eessi.io/api_data/data/',
        type: 'string',
      },
      {
        key: 'SOFTWARE_CATALOG_EESSI_INCLUDE_EXTENSIONS',
        description: translate('Include extension packages (Python, R packages, etc.) from EESSI'),
        default: true,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Software catalog Spack'),
    items: [
      {
        key: 'SOFTWARE_CATALOG_SPACK_UPDATE_ENABLED',
        description: translate('Enable automated daily updates for Spack software catalog'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'SOFTWARE_CATALOG_SPACK_VERSION',
        description: translate('Spack catalog version to load (auto-detect if empty)'),
        default: '',
        type: 'string',
      },
      {
        key: 'SOFTWARE_CATALOG_SPACK_DATA_URL',
        description: translate('URL for Spack repology.json data'),
        default: 'https://raw.githubusercontent.com/spack/packages.spack.io/refs/heads/gh-pages/data/repology.json',
        type: 'string',
      },
    ],
  },
  {
    description: translate('System Logging'),
    items: [
      {
        key: 'SYSTEM_LOG_ENABLED',
        description: translate('Enable storing system logs (API, Worker, Beat) in the database for staff viewing.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'SYSTEM_LOG_MAX_ROWS_PER_SOURCE',
        description: translate('Maximum number of log rows to keep per source (api, worker, beat). Oldest rows are deleted when exceeded.'),
        default: 5000,
        type: 'integer',
      },
    ],
  },
  {
    description: translate('Table Growth Monitoring'),
    items: [
      {
        key: 'TABLE_GROWTH_MONITORING_ENABLED',
        description: translate('Enable table growth monitoring to detect potential data leaks from bugs.'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'TABLE_GROWTH_WEEKLY_THRESHOLD_PERCENT',
        description: translate('Alert if a table grows by more than this percentage in a week.'),
        default: 50,
        type: 'integer',
      },
      {
        key: 'TABLE_GROWTH_MONTHLY_THRESHOLD_PERCENT',
        description: translate('Alert if a table grows by more than this percentage in a month.'),
        default: 200,
        type: 'integer',
      },
      {
        key: 'TABLE_GROWTH_RETENTION_DAYS',
        description: translate('Number of days to retain table size history data.'),
        default: 90,
        type: 'integer',
      },
      {
        key: 'TABLE_GROWTH_MIN_SIZE_BYTES',
        description: translate('Minimum table size in bytes (default 1MB) to monitor. Smaller tables are ignored.'),
        default: 1048576,
        type: 'integer',
      },
    ],
  },
  {
    description: translate('User Actions'),
    items: [
      {
        key: 'USER_ACTIONS_ENABLED',
        description: translate('Enable user actions notification system.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'USER_ACTIONS_PENDING_ORDER_HOURS',
        description: translate('Hours before pending order becomes a user action item (1-168).'),
        default: 24,
        type: 'integer',
      },
      {
        key: 'USER_ACTIONS_HIGH_URGENCY_NOTIFICATION',
        description: translate('Send digest notification if user has high urgency actions.'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'USER_ACTIONS_NOTIFICATION_THRESHOLD',
        description: translate('Send digest notification if user has more than N actions.'),
        default: 5,
        type: 'integer',
      },
      {
        key: 'USER_ACTIONS_EXECUTION_RETENTION_DAYS',
        description: translate('Number of days to keep action execution history.'),
        default: 90,
        type: 'integer',
      },
      {
        key: 'USER_ACTIONS_DEFAULT_EXPIRATION_REMINDERS',
        description: translate('Default reminder schedule (days before expiration) for expiring resources. Can be overridden per offering via plugin_options.resource_expiration_reminders.'),
        default: [30, 14, 7, 1],
        type: 'list_field',
      },
    ],
  },
  {
    description: translate('Arrow Integration'),
    items: [
      {
        key: 'ARROW_AUTO_RECONCILIATION',
        description: translate('Auto-apply compensations when Arrow validates billing'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'ARROW_SYNC_INTERVAL_HOURS',
        description: translate('Billing sync interval in hours'),
        default: 6,
        type: 'integer',
      },
      {
        key: 'ARROW_CONSUMPTION_SYNC_ENABLED',
        description: translate('Enable real-time consumption sync from Arrow API'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'ARROW_CONSUMPTION_SYNC_INTERVAL_HOURS',
        description: translate('Consumption sync interval in hours (default: hourly)'),
        default: 1,
        type: 'integer',
      },
      {
        key: 'ARROW_BILLING_CHECK_INTERVAL_HOURS',
        description: translate('Billing export check interval in hours for reconciliation'),
        default: 6,
        type: 'integer',
      },
    ],
  },
  {
    description: translate('SLURM Policy'),
    items: [
      {
        key: 'SLURM_POLICY_EVALUATION_LOG_RETENTION_DAYS',
        description: translate('Number of days to retain SLURM policy evaluation log entries before automatic cleanup.'),
        default: 90,
        type: 'integer',
      },
    ],
  },
  {
    description: translate('Usage Polling'),
    items: [
      {
        key: 'USAGE_POLL_RECORD_RETENTION_MONTHS',
        description: translate('Number of months to retain usage poll records before automatic cleanup.'),
        default: 3,
        type: 'integer',
      },
    ],
  },
  {
    description: translate('Identity Bridge'),
    items: [
      {
        key: 'FEDERATED_IDENTITY_SYNC_ENABLED',
        description: translate('Enable the Identity Bridge API for push-based ISD user attribute synchronization.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'FEDERATED_IDENTITY_SYNC_ALLOWED_ATTRIBUTES',
        description: translate('User attributes settable via Identity Bridge.'),
        default: ['first_name', 'last_name', 'email', 'organization', 'affiliations'],
        type: 'multiple_choice_field',
        options: [{ value: 'username', label: 'Username' }, { value: 'registration_method', label: 'Registration method' }, { value: 'first_name', label: 'First name' }, { value: 'last_name', label: 'Last name' }, { value: 'full_name', label: 'Full name' }, { value: 'email', label: 'Email' }, { value: 'phone_number', label: 'Phone number' }, { value: 'organization', label: 'Organization' }, { value: 'job_title', label: 'Job title' }, { value: 'affiliations', label: 'Affiliations' }, { value: 'gender', label: 'Gender' }, { value: 'personal_title', label: 'Personal title' }, { value: 'birth_date', label: 'Birth date' }, { value: 'place_of_birth', label: 'Place of birth' }, { value: 'country_of_residence', label: 'Country of residence' }, { value: 'nationality', label: 'Nationality' }, { value: 'nationalities', label: 'Nationalities' }, { value: 'organization_country', label: 'Organization country' }, { value: 'organization_type', label: 'Organization type' }, { value: 'organization_registry_code', label: 'Organization registry code' }, { value: 'eduperson_assurance', label: 'Eduperson assurance' }, { value: 'civil_number', label: 'Civil number' }, { value: 'identity_source', label: 'Identity source' }],
      },
      {
        key: 'FEDERATED_IDENTITY_DEACTIVATION_POLICY',
        description: translate('When to deactivate a federated user.'),
        default: 'any_isd_removed',
        type: 'choice_field',
        options: [{ value: 'all_isds_removed', label: 'All ISDs removed' }, { value: 'any_isd_removed', label: 'Any ISD removal' }],
      },
    ],
  },
  {
    description: translate('Project Digest'),
    items: [
      {
        key: 'ENABLE_PROJECT_DIGEST',
        description: translate('Enable project digest email notifications for organizations.'),
        default: false,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('SSH keys'),
    items: [
      {
        key: 'SSH_KEY_ALLOWED_TYPES',
        description: translate('List of allowed SSH key types. Empty list means all types are allowed.'),
        default: ['ssh-ed25519', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', 'ecdsa-sha2-nistp521', 'ssh-rsa', 'sk-ssh-ed25519@openssh.com', 'sk-ecdsa-sha2-nistp256@openssh.com'],
        type: 'multiple_choice_field',
        options: [{ value: 'ssh-ed25519', label: 'ssh-ed25519' }, { value: 'ecdsa-sha2-nistp256', label: 'ecdsa-sha2-nistp256' }, { value: 'ecdsa-sha2-nistp384', label: 'ecdsa-sha2-nistp384' }, { value: 'ecdsa-sha2-nistp521', label: 'ecdsa-sha2-nistp521' }, { value: 'ssh-rsa', label: 'ssh-rsa' }, { value: 'sk-ssh-ed25519@openssh.com', label: 'sk-ssh-ed25519@openssh.com' }, { value: 'sk-ecdsa-sha2-nistp256@openssh.com', label: 'sk-ecdsa-sha2-nistp256@openssh.com' }],
      },
      {
        key: 'SSH_KEY_MIN_RSA_KEY_SIZE',
        description: translate('Minimum allowed RSA key size in bits. Set to 0 to disable the check.'),
        default: 2048,
        type: 'integer',
      },
      {
        key: 'ENABLE_ISSUES_FOR_USER_SSH_KEY_CHANGES',
        description: translate('If true, a support ticket is created when a user adds or removes an SSH public key.'),
        default: false,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Reporting'),
    items: [
      {
        key: 'ENABLED_REPORTING_SCREENS',
        description: translate('Select which reporting screens should be visible to users. Uncheck to disable specific reports.'),
        default: ['resource-usage', 'user-usage', 'quotas', 'usage-monitoring', 'usage-trends', 'organization-summary', 'project-detail', 'resources-geography', 'project-classification', 'usage-by-customer', 'usage-by-org-type', 'usage-by-creator', 'call-performance', 'review-progress', 'resource-demand', 'capacity', 'provider-overview', 'provider-revenue', 'provider-orders', 'provider-resources', 'provider-customers', 'provider-offerings', 'openstack-instances', 'offering-usage', 'user-analytics', 'user-demographics', 'user-organizations', 'user-affiliations', 'user-roles', 'growth', 'revenue', 'pricelist', 'orders', 'offering-costs', 'maintenance-overview', 'provisioning-stats'],
        type: 'multiple_choice_field',
        options: [{ value: 'resource-usage', label: 'Resources: Usage' }, { value: 'user-usage', label: 'Resources: Usage by user' }, { value: 'quotas', label: 'Resources: Quotas' }, { value: 'usage-monitoring', label: 'Resources: Usage monitoring' }, { value: 'usage-trends', label: 'Resources: Usage trends' }, { value: 'organization-summary', label: 'Resources: Organization summary' }, { value: 'project-detail', label: 'Resources: Project detail' }, { value: 'resources-geography', label: 'Resources: Geographic distribution' }, { value: 'project-classification', label: 'Resources: Project classification' }, { value: 'usage-by-customer', label: 'Resources: Usage by customer' }, { value: 'usage-by-org-type', label: 'Resources: Usage by organization type' }, { value: 'usage-by-creator', label: 'Resources: Usage by creator' }, { value: 'call-performance', label: 'Proposals: Call performance' }, { value: 'review-progress', label: 'Proposals: Review progress' }, { value: 'resource-demand', label: 'Proposals: Resource demand' }, { value: 'capacity', label: 'Provider: Capacity' }, { value: 'provider-overview', label: 'Provider: Provider overview' }, { value: 'provider-revenue', label: 'Provider: Provider revenue' }, { value: 'provider-orders', label: 'Provider: Provider orders' }, { value: 'provider-resources', label: 'Provider: Provider resources' }, { value: 'provider-customers', label: 'Provider: Provider customers' }, { value: 'provider-offerings', label: 'Provider: Provider offerings' }, { value: 'openstack-instances', label: 'Provider: OpenStack instances' }, { value: 'offering-usage', label: 'Provider: Offering component usage' }, { value: 'user-analytics', label: 'Users: Analytics' }, { value: 'user-demographics', label: 'Users: Demographics' }, { value: 'user-organizations', label: 'Users: Organizations' }, { value: 'user-affiliations', label: 'Users: Affiliations' }, { value: 'user-roles', label: 'Users: Role distribution' }, { value: 'growth', label: 'Financial: Growth' }, { value: 'revenue', label: 'Financial: Monthly revenue' }, { value: 'pricelist', label: 'Financial: Pricelist' }, { value: 'orders', label: 'Financial: Orders' }, { value: 'offering-costs', label: 'Financial: Offering costs' }, { value: 'maintenance-overview', label: 'Operations: Maintenance overview' }, { value: 'provisioning-stats', label: 'Operations: Provisioning statistics' }],
      },
    ],
  },
  {
    description: translate('Personal Access Tokens'),
    items: [
      {
        key: 'PAT_ENABLED',
        description: translate('Enable Personal Access Token authentication.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'PAT_MAX_LIFETIME_DAYS',
        description: translate('Maximum PAT lifetime in days.'),
        default: 365,
        type: 'integer',
      },
      {
        key: 'PAT_MAX_TOKENS_PER_USER',
        description: translate('Maximum number of active PATs per user.'),
        default: 20,
        type: 'integer',
      },
    ],
  },
];

