// WARNING: This file is auto-generated from src/waldur_core/core/management/commands/print_settings_description.py
// Do not edit it manually. All manual changes would be overridden.
import { translate } from '@waldur/i18n';

export const SettingsDescription = [
  {
    description: translate('Branding'),
    items: [
      {
        key: 'SITE_NAME',
        description: translate('Human-friendly name of the Waldur deployment.'),
        default: 'Waldur',
        type: 'string',
      },
      {
        key: 'SHORT_PAGE_TITLE',
        description: translate('It is used as prefix for page title.'),
        default: 'Waldur',
        type: 'string',
      },
      {
        key: 'FULL_PAGE_TITLE',
        description: translate('It is used as default page title if it\'s not specified explicitly.'),
        default: 'Waldur | Cloud Service Management',
        type: 'string',
      },
      {
        key: 'SITE_DESCRIPTION',
        description: translate('Description of the Waldur deployment.'),
        default: 'Your single pane of control for managing projects, teams and resources in a self-service manner.',
        type: 'string',
      },
      {
        key: 'HOMEPORT_URL',
        description: translate('It is used for rendering callback URL in HomePort'),
        default: 'https://example.com/',
        type: 'string',
      },
      {
        key: 'RANCHER_USERNAME_INPUT_LABEL',
        description: translate('Label for the username field in Rancher external user resource access management.'),
        default: 'Username',
        type: 'string',
      },
    ],
  },
  {
    description: translate('Marketplace Branding'),
    items: [
      {
        key: 'SITE_ADDRESS',
        description: translate('It is used in marketplace order header.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SITE_EMAIL',
        description: translate('It is used in marketplace order header and UI footer.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SITE_PHONE',
        description: translate('It is used in marketplace order header and UI footer.'),
        default: '',
        type: 'string',
      },
      {
        key: 'CURRENCY_NAME',
        description: translate('It is used in marketplace order details and invoices for currency formatting.'),
        default: 'EUR',
        type: 'string',
      },
      {
        key: 'MARKETPLACE_LANDING_PAGE',
        description: translate('Marketplace landing page title.'),
        default: 'Marketplace',
        type: 'string',
      },
      {
        key: 'COUNTRIES',
        description: translate('It is used in organization creation dialog in order to limit country choices to predefined set.'),
        default: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'EU', 'FI', 'FR', 'GB', 'GE', 'GR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LT', 'LU', 'LV', 'MC', 'MK', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'UA'],
        type: 'country_list_field',
      },
    ],
  },
  {
    description: translate('Marketplace'),
    items: [
      {
        key: 'THUMBNAIL_SIZE',
        description: translate('Size of the thumbnail to generate when screenshot is uploaded for an offering.'),
        default: '120x120',
        type: 'string',
      },
      {
        key: 'ANONYMOUS_USER_CAN_VIEW_OFFERINGS',
        description: translate('Allow anonymous users to see shared offerings in active, paused and archived states'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'ANONYMOUS_USER_CAN_VIEW_PLANS',
        description: translate('Allow anonymous users to see plans'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'NOTIFY_STAFF_ABOUT_APPROVALS',
        description: translate('If true, users with staff role are notified when request for order approval is generated'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'NOTIFY_ABOUT_RESOURCE_CHANGE',
        description: translate('If true, notify users about resource changes from Marketplace perspective. Can generate duplicate events if plugins also log'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'DISABLE_SENDING_NOTIFICATIONS_ABOUT_RESOURCE_UPDATE',
        description: translate('Disable only resource update events.'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'ENABLE_STALE_RESOURCE_NOTIFICATIONS',
        description: translate('Enable reminders to owners about resources of shared offerings that have not generated any cost for the last 3 months.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'ENABLE_MOCK_SERVICE_ACCOUNT_BACKEND',
        description: translate('Enable mock returns for the service account service'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'ENABLE_MOCK_COURSE_ACCOUNT_BACKEND',
        description: translate('Enable mock returns for the course account service'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'ENFORCE_USER_CONSENT_FOR_OFFERINGS',
        description: translate('If True, users must have active consent to access offerings that have active Terms of Service.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'DISABLED_OFFERING_TYPES',
        description: translate('List of offering types disabled for creation and selection.'),
        default: [],
        type: 'list_field',
      },
      {
        key: 'ENABLE_ORDER_START_DATE',
        description: translate('Allow setting start date to control when resource creation order is processed.'),
        default: false,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Project'),
    items: [
      {
        key: 'PROJECT_END_DATE_MANDATORY',
        description: translate('If true, project end date field becomes mandatory when creating or updating projects.'),
        default: false,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Telemetry'),
    items: [
      {
        key: 'TELEMETRY_URL',
        description: translate('URL for sending telemetry data.'),
        default: 'https://telemetry.waldur.com/',
        type: 'string',
      },
      {
        key: 'TELEMETRY_VERSION',
        description: translate('Telemetry service version.'),
        default: 1,
        type: 'integer',
      },
    ],
  },
  {
    description: translate('Custom Scripts'),
    items: [
      {
        key: 'SCRIPT_RUN_MODE',
        description: translate('Type of jobs deployment. Valid values: "docker" for simple docker deployment, "k8s" for Kubernetes-based one'),
        default: 'docker',
        type: 'string',
      },
      {
        key: 'DOCKER_CLIENT',
        description: translate('Options for docker client. See also: <https://docker-py.readthedocs.io/en/stable/client.html#docker.client.DockerClient>'),
        default: {'base_url': 'unix:///var/run/docker.sock'},
        type: 'dict_field',
      },
      {
        key: 'DOCKER_RUN_OPTIONS',
        description: translate('Options for docker runtime. See also: <https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.run>'),
        default: {'mem_limit': '512m'},
        type: 'dict_field',
      },
      {
        key: 'DOCKER_SCRIPT_DIR',
        description: translate('Path to folder on executor machine where to create temporary submission scripts. If None, uses OS-dependent location. OS X users, see <https://github.com/docker/for-mac/issues/1532>'),
        default: '',
        type: 'string',
      },
      {
        key: 'DOCKER_REMOVE_CONTAINER',
        description: translate('Remove Docker container after script execution'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'DOCKER_IMAGES',
        description: translate('Key is command to execute script, value is a dictionary of image name and command.'),
        default: {'python': {'image': 'python:3.11-alpine', 'command': 'python'}, 'shell': {'image': 'alpine:3', 'command': 'sh'}, 'ansible': {'image': 'alpine/ansible:2.18.6', 'command': 'ansible-playbook'}},
        type: 'dict_field',
      },
      {
        key: 'DOCKER_VOLUME_NAME',
        description: translate('A name of the shared volume to store scripts'),
        default: 'waldur-docker-compose_waldur_script_launchzone',
        type: 'string',
      },
      {
        key: 'K8S_NAMESPACE',
        description: translate('Kubernetes namespace where jobs will be executed'),
        default: 'default',
        type: 'string',
      },
      {
        key: 'K8S_CONFIG_PATH',
        description: translate('Path to Kubernetes configuration file'),
        default: '~/.kube/config',
        type: 'string',
      },
      {
        key: 'K8S_JOB_TIMEOUT',
        description: translate('Timeout for execution of one Kubernetes job in seconds'),
        default: 1800,
        type: 'integer',
      },
    ],
  },
  {
    description: translate('Notifications'),
    items: [
      {
        key: 'COMMON_FOOTER_TEXT',
        description: translate('Common footer in txt format for all emails.'),
        default: '',
        type: 'text_field',
      },
      {
        key: 'COMMON_FOOTER_HTML',
        description: translate('Common footer in html format for all emails.'),
        default: '',
        type: 'html_field',
      },
      {
        key: 'MAINTENANCE_ANNOUNCEMENT_NOTIFY_BEFORE_MINUTES',
        description: translate('How many minutes before scheduled maintenance users should be notified.'),
        default: 60,
        type: 'integer',
      },
      {
        key: 'MAINTENANCE_ANNOUNCEMENT_NOTIFY_SYSTEM',
        description: translate('How maintenance notifications are delivered. Choices: AdminAnnouncement or BroadcastMessage.'),
        default: ['AdminAnnouncement'],
        type: 'list_field',
      },
    ],
  },
  {
    description: translate('Links'),
    items: [
      {
        key: 'DOCS_URL',
        description: translate('Renders link to docs in header'),
        default: '',
        type: 'url_field',
      },
      {
        key: 'HERO_LINK_LABEL',
        description: translate('Label for link in hero section of HomePort landing page. It can be lead to support site or blog post.'),
        default: '',
        type: 'string',
      },
      {
        key: 'HERO_LINK_URL',
        description: translate('Link URL in hero section of HomePort landing page.'),
        default: '',
        type: 'url_field',
      },
      {
        key: 'SUPPORT_PORTAL_URL',
        description: translate('Link URL to support portal. Rendered as a shortcut on dashboard'),
        default: '',
        type: 'url_field',
      },
    ],
  },
  {
    description: translate('Theme'),
    items: [
      {
        key: 'SIDEBAR_STYLE',
        description: translate('Style of sidebar. Possible values: dark, light, accent.'),
        default: 'dark',
        type: 'string',
      },
      {
        key: 'BRAND_COLOR',
        description: translate('Brand color is used for button background.'),
        default: '#307300',
        type: 'color_field',
      },
      {
        key: 'DISABLE_DARK_THEME',
        description: translate('Toggler to disable dark theme.'),
        default: false,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Images'),
    items: [
      {
        key: 'SITE_LOGO',
        description: translate('The image used in marketplace order header.'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'SIDEBAR_LOGO',
        description: translate('The image rendered at the top of sidebar menu in HomePort.'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'SIDEBAR_LOGO_MOBILE',
        description: translate('The image rendered at the top of mobile sidebar menu in HomePort.'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'SIDEBAR_LOGO_DARK',
        description: translate('The image rendered at the top of sidebar menu in dark mode.'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'POWERED_BY_LOGO',
        description: translate('The image rendered at the bottom of login menu in HomePort.'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'HERO_IMAGE',
        description: translate('The image rendered at hero section of HomePort landing page.'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'MARKETPLACE_HERO_IMAGE',
        description: translate('The image rendered at hero section of Marketplace landing page. Please, use a wide image (min. 1920×600px) with no text or logos. Keep the center area clean, and choose a darker image for dark mode or a brighter image for light mode.'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'CALL_MANAGEMENT_HERO_IMAGE',
        description: translate('The image rendered at hero section of Call Management landing page. Please, use a wide image (min. 1920×600px) with no text or logos. Keep the center area clean, and choose a darker image for dark mode or a brighter image for light mode.'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'LOGIN_LOGO',
        description: translate('A custom .png image file for login page'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'FAVICON',
        description: translate('A custom favicon .png image file'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'OFFERING_LOGO_PLACEHOLDER',
        description: translate('Default logo for offering'),
        default: '',
        type: 'image_field',
      },
      {
        key: 'KEYCLOAK_ICON',
        description: translate('A custom PNG icon for Keycloak login button'),
        default: '',
        type: 'image_field',
      },
    ],
  },
  {
    description: translate('Service desk integration settings'),
    items: [
      {
        key: 'WALDUR_SUPPORT_ENABLED',
        description: translate('Toggler for support plugin.'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'WALDUR_SUPPORT_ACTIVE_BACKEND_TYPE',
        description: translate('Type of support backend. Possible values: atlassian, zammad, smax.'),
        default: 'atlassian',
        type: 'string',
      },
      {
        key: 'WALDUR_SUPPORT_DISPLAY_REQUEST_TYPE',
        description: translate('Toggler for request type displaying'),
        default: true,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Atlassian settings'),
    items: [
      {
        key: 'ATLASSIAN_API_URL',
        description: translate('Atlassian API server URL'),
        default: 'https://example.com/',
        type: 'url_field',
      },
      {
        key: 'ATLASSIAN_USERNAME',
        description: translate('Username for access user'),
        default: 'USERNAME',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_PASSWORD',
        description: translate('Password for access user'),
        default: 'PASSWORD',
        type: 'secret_field',
      },
      {
        key: 'ATLASSIAN_EMAIL',
        description: translate('Email for access user'),
        default: '',
        type: 'email_field',
      },
      {
        key: 'ATLASSIAN_TOKEN',
        description: translate('Token for access user'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'ATLASSIAN_PERSONAL_ACCESS_TOKEN',
        description: translate('Personal Access Token for user'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'ATLASSIAN_OAUTH2_CLIENT_ID',
        description: translate('OAuth 2.0 Client ID'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'ATLASSIAN_OAUTH2_ACCESS_TOKEN',
        description: translate('OAuth 2.0 Access Token'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'ATLASSIAN_OAUTH2_TOKEN_TYPE',
        description: translate('OAuth 2.0 Token Type'),
        default: 'Bearer',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_PROJECT_ID',
        description: translate('Service desk ID or key'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_DEFAULT_OFFERING_ISSUE_TYPE',
        description: translate('Issue type used for request-based item processing.'),
        default: 'Service Request',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_EXCLUDED_ATTACHMENT_TYPES',
        description: translate('Comma-separated list of file extenstions not allowed for attachment.'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_ISSUE_TYPES',
        description: translate('Comma-separated list of enabled issue types. First type is the default one.'),
        default: 'Informational, Service Request, Change Request, Incident',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_SUPPORT_TYPE_MAPPING',
        description: translate('Mapping from frontend issue types to backend request types'),
        default: {'Informational': 'Get IT help', 'Service Request': 'Request new software', 'Change Request': 'Change Request', 'Incident': 'Report a system problem'},
        type: 'dict_field',
      },
      {
        key: 'ATLASSIAN_AFFECTED_RESOURCE_FIELD',
        description: translate('Affected resource field name'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_DESCRIPTION_TEMPLATE',
        description: translate('Template for issue description'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_SUMMARY_TEMPLATE',
        description: translate('Template for issue summary'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_IMPACT_FIELD',
        description: translate('Impact field name'),
        default: 'Impact',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_ORGANISATION_FIELD',
        description: translate('Organisation field name'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_RESOLUTION_SLA_FIELD',
        description: translate('Resolution SLA field name'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_PROJECT_FIELD',
        description: translate('Project field name'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_REPORTER_FIELD',
        description: translate('Reporter field name'),
        default: 'Original Reporter',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_CALLER_FIELD',
        description: translate('Caller field name'),
        default: 'Caller',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_SLA_FIELD',
        description: translate('SLA field name'),
        default: 'Time to first response',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_LINKED_ISSUE_TYPE',
        description: translate('Type of linked issue field name'),
        default: 'Relates',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_SATISFACTION_FIELD',
        description: translate('Customer satisfaction field name'),
        default: 'Customer satisfaction',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_REQUEST_FEEDBACK_FIELD',
        description: translate('Request feedback field name'),
        default: 'Request feedback',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_TEMPLATE_FIELD',
        description: translate('Template field name'),
        default: '',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_WALDUR_BACKEND_ID_FIELD',
        description: translate('Waldur backend ID custom field ID (fallback when field lookup by name fails)'),
        default: 'customfield_10200',
        type: 'string',
      },
      {
        key: 'ATLASSIAN_CUSTOM_ISSUE_FIELD_MAPPING_ENABLED',
        description: translate('Should extra issue field mappings be applied'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'ATLASSIAN_SHARED_USERNAME',
        description: translate('Is Service Desk username the same as in Waldur'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'ATLASSIAN_VERIFY_SSL',
        description: translate('Toggler for SSL verification'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'ATLASSIAN_USE_OLD_API',
        description: translate('Toggler for legacy API usage.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'ATLASSIAN_MAP_WALDUR_USERS_TO_SERVICEDESK_AGENTS',
        description: translate('Toggler for mapping between waldur user and service desk agents.'),
        default: false,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Zammad settings'),
    items: [
      {
        key: 'ZAMMAD_API_URL',
        description: translate('Zammad API server URL. For example <https://localhost:8080/>'),
        default: '',
        type: 'url_field',
      },
      {
        key: 'ZAMMAD_TOKEN',
        description: translate('Authorization token.'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'ZAMMAD_GROUP',
        description: translate('The name of the group to which the ticket will be added. If not specified, the first group will be used.'),
        default: '',
        type: 'string',
      },
      {
        key: 'ZAMMAD_ARTICLE_TYPE',
        description: translate('Type of a comment. Default is email because it allows support to reply to tickets directly in Zammad<https://docs.zammad.org/en/latest/api/ticket/articles.html#articles/>'),
        default: 'email',
        type: 'string',
      },
      {
        key: 'ZAMMAD_COMMENT_MARKER',
        description: translate('Marker for comment. Used for separating comments made via Waldur from natively added comments.'),
        default: 'Created by Waldur',
        type: 'string',
      },
      {
        key: 'ZAMMAD_COMMENT_PREFIX',
        description: translate('Comment prefix with user info.'),
        default: 'User: {name}',
        type: 'string',
      },
      {
        key: 'ZAMMAD_COMMENT_COOLDOWN_DURATION',
        description: translate('Time in minutes. Time in minutes while comment deletion is available <https://github.com/zammad/zammad/issues/2687/>, <https://github.com/zammad/zammad/issues/3086/>'),
        default: 5,
        type: 'integer',
      },
    ],
  },
  {
    description: translate('SMAX settings'),
    items: [
      {
        key: 'SMAX_API_URL',
        description: translate('SMAX API server URL. For example <https://localhost:8080/>'),
        default: '',
        type: 'url_field',
      },
      {
        key: 'SMAX_TENANT_ID',
        description: translate('User tenant ID.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SMAX_LOGIN',
        description: translate('Authorization login.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SMAX_PASSWORD',
        description: translate('Authorization password.'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'SMAX_ORGANISATION_FIELD',
        description: translate('Organisation field name.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SMAX_PROJECT_FIELD',
        description: translate('Project field name.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SMAX_AFFECTED_RESOURCE_FIELD',
        description: translate('Resource field name.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SMAX_REQUESTS_OFFERING',
        description: translate('Requests offering code for all issues.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SMAX_SECONDS_TO_WAIT',
        description: translate('Duration in seconds of delay between pull user attempts.'),
        default: 1,
        type: 'integer',
      },
      {
        key: 'SMAX_TIMES_TO_PULL',
        description: translate('The maximum number of attempts to pull user from backend.'),
        default: 10,
        type: 'integer',
      },
      {
        key: 'SMAX_CREATION_SOURCE_NAME',
        description: translate('Creation source name.'),
        default: '',
        type: 'string',
      },
      {
        key: 'SMAX_VERIFY_SSL',
        description: translate('Toggler for SSL verification'),
        default: true,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('Proposal settings'),
    items: [
      {
        key: 'PROPOSAL_REVIEW_DURATION',
        description: translate('Review duration in days.'),
        default: 7,
        type: 'integer',
      },
    ],
  },
  {
    description: translate('Table settings'),
    items: [
      {
        key: 'USER_TABLE_COLUMNS',
        description: translate('Comma-separated list of columns for users table.'),
        default: '',
        type: 'string',
      },
    ],
  },
  {
    description: translate('Localization'),
    items: [
      {
        key: 'LANGUAGE_CHOICES',
        description: translate('List of enabled languages'),
        default: 'en,et,lt,lv,ru,it,de,da,sv,es,fr,nb,ar,cs',
        type: 'string',
      },
    ],
  },
  {
    description: translate('User settings'),
    items: [
      {
        key: 'AUTO_APPROVE_USER_TOS',
        description: translate('Mark terms of services as approved for new users.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'ENABLE_STRICT_CHECK_ACCEPTING_INVITATION',
        description: translate('If true, user email in Waldur database and in invitatation must strictly match.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'INVITATION_DISABLE_MULTIPLE_ROLES',
        description: translate('Do not allow user to accept multiple roles within the same scope (project or organization) using invitation. When enabled, users can still accept invitations to different scopes but cannot have multiple roles in the same scope.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'DEFAULT_IDP',
        description: translate('Triggers authentication flow at once.'),
        default: '',
        type: 'string',
      },
      {
        key: 'DEACTIVATE_USER_IF_NO_ROLES',
        description: translate('Deactivate user if all roles are revoked (except staff/support)'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'OIDC_BLOCK_CREATION_OF_UNINVITED_USERS',
        description: translate('If true, block creation of an account on OIDC login if user email is not provided or provided and is not in the list of one of the active invitations.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'OIDC_ACCESS_TOKEN_ENABLED',
        description: translate('If true, OIDC complete view returns access token instead of Waldur token'),
        default: false,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('FreeIPA settings'),
    items: [
      {
        key: 'FREEIPA_ENABLED',
        description: translate('Enable integration of identity provisioning in configured FreeIPA.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'FREEIPA_HOSTNAME',
        description: translate('Hostname of FreeIPA server.'),
        default: 'ipa.example.com',
        type: 'string',
      },
      {
        key: 'FREEIPA_USERNAME',
        description: translate('Username of FreeIPA user with administrative privileges.'),
        default: 'admin',
        type: 'string',
      },
      {
        key: 'FREEIPA_PASSWORD',
        description: translate('Password of FreeIPA user with administrative privileges'),
        default: 'secret',
        type: 'secret_field',
      },
      {
        key: 'FREEIPA_VERIFY_SSL',
        description: translate('Validate TLS certificate of FreeIPA web interface / REST API'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'FREEIPA_USERNAME_PREFIX',
        description: translate('Prefix to be appended to all usernames created in FreeIPA by Waldur'),
        default: 'waldur_',
        type: 'string',
      },
      {
        key: 'FREEIPA_GROUPNAME_PREFIX',
        description: translate('Prefix to be appended to all group names created in FreeIPA by Waldur'),
        default: 'waldur_',
        type: 'string',
      },
      {
        key: 'FREEIPA_BLACKLISTED_USERNAMES',
        description: translate('List of username that users are not allowed to select'),
        default: ['root'],
        type: 'list_field',
      },
      {
        key: 'FREEIPA_GROUP_SYNCHRONIZATION_ENABLED',
        description: translate('Optionally disable creation of user groups in FreeIPA matching Waldur structure'),
        default: true,
        type: 'boolean',
      },
    ],
  },
  {
    description: translate('OIDC auth settings'),
    items: [
      {
        key: 'OIDC_AUTH_URL',
        description: translate('OIDC authentication endpoint URL.'),
        default: '',
        type: 'string',
      },
      {
        key: 'OIDC_INTROSPECTION_URL',
        description: translate('OIDC introspection endpoint URL for validating access tokens.'),
        default: '',
        type: 'string',
      },
      {
        key: 'OIDC_CLIENT_ID',
        description: translate('Client ID for authenticating against the introspection endpoint.'),
        default: '',
        type: 'string',
      },
      {
        key: 'OIDC_CLIENT_SECRET',
        description: translate('Client secret for authenticating against the introspection endpoint.'),
        default: '',
        type: 'string',
      },
      {
        key: 'OIDC_USER_FIELD',
        description: translate('Field name from the introspection response to identify the user (e.g., \'username\', \'email\', \'client_id\').'),
        default: 'username',
        type: 'string',
      },
      {
        key: 'OIDC_CACHE_TIMEOUT',
        description: translate('Number of seconds to cache token introspection results.'),
        default: 300,
        type: 'integer',
      },
    ],
  },
  {
    description: translate('Onboarding settings'),
    items: [
      {
        key: 'ONBOARDING_COUNTRY',
        description: translate('ISO 3166-1 alpha-2 country code for the deployment (e.g., \'EE\' for Estonia, \'AT\' for Austria). Used for onboarding and localization.'),
        default: '',
        type: 'string',
      },
      {
        key: 'ONBOARDING_VERIFICATION_EXPIRY_HOURS',
        description: translate('Number of hours after which onboarding verifications expire.'),
        default: 48,
        type: 'integer',
      },
      {
        key: 'ONBOARDING_ARIREGISTER_BASE_URL',
        description: translate('Base URL for Estonian Äriregister API endpoint.'),
        default: 'https://demo-ariregxmlv6.rik.ee/',
        type: 'url_field',
      },
      {
        key: 'ONBOARDING_ARIREGISTER_USERNAME',
        description: translate('Username for Estonian Äriregister API authentication.'),
        default: '',
        type: 'string',
      },
      {
        key: 'ONBOARDING_ARIREGISTER_PASSWORD',
        description: translate('Password for Estonian Äriregister API authentication.'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'ONBOARDING_ARIREGISTER_TIMEOUT',
        description: translate('Timeout in seconds for Estonian Äriregister API requests.'),
        default: 30,
        type: 'integer',
      },
      {
        key: 'ONBOARDING_WICO_API_URL',
        description: translate('WirtschaftsCompass API server URL'),
        default: 'https://api.wirtschaftscompass.at/',
        type: 'url_field',
      },
      {
        key: 'ONBOARDING_WICO_TOKEN',
        description: translate('WirtschaftsCompass API token'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'ONBOARDING_BOLAGSVERKET_API_URL',
        description: translate('Sweden Business Register API server URL'),
        default: 'https://gw-accept2.api.bolagsverket.se/',
        type: 'url_field',
      },
      {
        key: 'ONBOARDING_BOLAGSVERKET_TOKEN_API_URL',
        description: translate('Bolagsverket OAuth2 token server base URL'),
        default: 'https://portal-accept2.api.bolagsverket.se/',
        type: 'url_field',
      },
      {
        key: 'ONBOARDING_BOLAGSVERKET_CLIENT_ID',
        description: translate('Sweden Business Register API client identifier'),
        default: '',
        type: 'string',
      },
      {
        key: 'ONBOARDING_BOLAGSVERKET_CLIENT_SECRET',
        description: translate('Sweden Business Register API client secret'),
        default: '',
        type: 'secret_field',
      },
      {
        key: 'ONBOARDING_BREG_API_URL',
        description: translate('Norway Business Register API server URL'),
        default: 'https://data.brreg.no/',
        type: 'url_field',
      },
    ],
  },
  {
    description: translate('LLM inference settings'),
    items: [
      {
        key: 'LLM_CHAT_ENABLED',
        description: translate('Enable LLM-based chat feature and calls to the inference service.'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'LLM_INFERENCES_BACKEND_TYPE',
        description: translate('Type of LLM inference backend. For example: openai, ollama.'),
        default: 'ollama',
        type: 'string',
      },
      {
        key: 'LLM_INFERENCES_API_URL',
        description: translate('Base URL for LLM inference service API.'),
        default: '',
        type: 'url_field',
      },
      {
        key: 'LLM_INFERENCES_API_TOKEN',
        description: translate('API key for authenticating with the LLM inference service.'),
        default: '',
        type: 'string',
      },
      {
        key: 'LLM_INFERENCES_MODEL',
        description: translate('Name of the LLM model to use for inference.'),
        default: 'gemma3:27b',
        type: 'string',
      },
    ],
  },
  {
    description: translate('Software catalog settings'),
    items: [
      {
        key: 'SOFTWARE_CATALOG_EESSI_UPDATE_ENABLED',
        description: translate('Enable automated daily updates for EESSI software catalog'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'SOFTWARE_CATALOG_EESSI_VERSION',
        description: translate('EESSI catalog version to load (auto-detect if empty)'),
        default: '',
        type: 'string',
      },
      {
        key: 'SOFTWARE_CATALOG_EESSI_API_URL',
        description: translate('Base URL for EESSI API data'),
        default: 'https://www.eessi.io/api_data/data/',
        type: 'string',
      },
      {
        key: 'SOFTWARE_CATALOG_EESSI_INCLUDE_EXTENSIONS',
        description: translate('Include extension packages (Python, R packages, etc.) from EESSI'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'SOFTWARE_CATALOG_SPACK_UPDATE_ENABLED',
        description: translate('Enable automated daily updates for Spack software catalog'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'SOFTWARE_CATALOG_SPACK_VERSION',
        description: translate('Spack catalog version to load (auto-detect if empty)'),
        default: '',
        type: 'string',
      },
      {
        key: 'SOFTWARE_CATALOG_SPACK_DATA_URL',
        description: translate('URL for Spack repology.json data'),
        default: 'https://raw.githubusercontent.com/spack/packages.spack.io/refs/heads/gh-pages/data/repology.json',
        type: 'string',
      },
      {
        key: 'SOFTWARE_CATALOG_UPDATE_EXISTING_PACKAGES',
        description: translate('Update existing packages during catalog refresh'),
        default: true,
        type: 'boolean',
      },
      {
        key: 'SOFTWARE_CATALOG_CLEANUP_ENABLED',
        description: translate('Enable automatic cleanup of old catalog data'),
        default: false,
        type: 'boolean',
      },
      {
        key: 'SOFTWARE_CATALOG_RETENTION_DAYS',
        description: translate('Number of days to retain old catalog versions'),
        default: 90,
        type: 'integer',
      },
    ],
  },
];
