import sparkline from './components/sparkline/sparkline';
import featuresModule from './components/features/module';
import teamModule from './components/team/module';
import issuesModule from './components/issues/module';
import userModule from './components/user/module';
import providersModule from './components/providers/module';
import projectModule from './components/project/module';
import navigationModule from './components/navigation/module';
import resourceModule from './components/resource/module';
import invoicesModule from './components/invoices/module';
import authModule from './components/auth/module';
import invitationsModule from './components/invitations/module';
import appstoreModule from './components/appstore/module';
import formModule from './components/form/module';
import openstackModule from './components/openstack/module';
import digitaloceanModule from './components/digitalocean/module';
import premiumSupportModule from './components/premiumSupport/module';
import customerModule from './components/customer/module';
import plansModule from './components/plans/module';
import eventsModule from './components/events/module';
import alertsModule from './components/alerts/module';
import routesModule from './routes/module';
import analyticsModule from './components/analytics/module';
import offeringsModule from './components/offering/module';
import helpModule from './components/help/module';
import coreModule from './components/core/module';
import dashboardModule from './components/dashboard/module';
import filtersModule from './components/core/filters';
import quotasModule from './components/quotas/module';
import bootstrap from './components/core/bootstrap';
import errorModule from './components/error/module';

const module = angular.module('ncsaas');

module.directive('sparkline', sparkline);
featuresModule(module);
teamModule(module);
issuesModule(module);
userModule(module);
providersModule(module);
projectModule(module);
navigationModule(module);
resourceModule(module);
invoicesModule(module);
authModule(module);
invitationsModule(module);
appstoreModule(module);
formModule(module);
openstackModule(module);
digitaloceanModule(module);
premiumSupportModule(module);
customerModule(module);
plansModule(module);
eventsModule(module);
alertsModule(module);
routesModule(module);
analyticsModule(module);
offeringsModule(module);
helpModule(module);
coreModule(module);
dashboardModule(module);
filtersModule(module);
quotasModule(module);
errorModule(module);

bootstrap('ncsaas');
