import $ from 'jquery';
window.$ = window.jQuery = $;
import angular from 'angular';
window.angular = angular;
window.gettext = angular.identity;
import 'angular-cron-jobs';
import 'angular-cron-jobs/dist/angular-cron-jobs.css';
import 'angular-animate';
import 'angular-block-ui';
import 'angular-cookies';
import 'angular-loader';
import 'angular-gravatar';
import 'angular-flash-alert';
import moment from 'moment';
window.moment = moment;
import 'angulartics';
import 'angulartics-google-analytics';
import 'angular-moment';
import 'angular-resource';
import 'angular-scroll';
import 'angular-ui-router';
import 'ui-select';
import 'satellizer';
import 'angular-translate';
import 'angular-translate-storage-cookie';
import 'angular-translate-storage-local';
import 'angular-translate-loader-static-files';
import 'ng-file-upload';
import 'angular-xeditable';
import 'angular-sanitize';
import 'leaflet';
import 'd3';
import 'angular-leaflet-directive';
import 'angular-ui-bootstrap';
import 'angular-bind-html-compile-ci-dev';

import 'jszip';
import 'datatables.net';
import 'datatables.net-bs';
import 'datatables.net-buttons';
import 'datatables.net-buttons/js/buttons.html5';
import 'datatables.net-buttons/js/buttons.print';
import 'datatables.net-buttons-bs';
import 'datatables.net-responsive';
import 'datatables.net-responsive-bs';
